In [1]:
# Standard library imports
import os
import shutil
import glob
from pathlib import Path
import logging


# Third-party library imports
import micom
from micom import Community
from cobra import Reaction, Metabolite, Model
from cobra.io import load_json_model, save_json_model, load_matlab_model, save_matlab_model, read_sbml_model, write_sbml_model
import cobra
import pandas as pd


# Load individual models
#model_bin1 = micom.util.load_model('models/bin.1.xml')
#model_bin2 = micom.util.load_model('models/bin.2.xml')
#model_bin3 = micom.util.load_model('models/bin.3.xml')
#model_bin4 = micom.util.load_model('models/bin.4.xml')
#model_bin5 = micom.util.load_model('models/bin.5.xml')
#model_bin6 = micom.util.load_model('models/bin.6.xml')
#model_bin7 = micom.util.load_model('models/bin.7.xml')
#model_bin8 = micom.util.load_model('models/bin.8.xml')

In [2]:


# params
model_db_path = Path("./models/")       # Replace with your actual model directory path
adjusted_models_path = Path("./adjusted_models/")  # Replace with your desired output directory path


medium = {
    'EX_cpd00063_e0': 100.0,     # Ca+
    'EX_cpd00099_e0': 100.0,     # Cl-
    'EX_cpd00137_e0': 5.0,       # Citrate
    'EX_cpd00009_e0': 100.0,     # Phosphate
    'EX_cpd00205_e0': 100.0,     # K+
    'EX_cpd11632_e0': 100.0,     # Photon
    'EX_cpd00254_e0': 100.0,     # Mg
    'EX_cpd10516_e0': 1.0,       # Fe3+
    'EX_cpd00013_e0': 100.0,     # Ammonium
    'EX_cpd00007_e0': 100.0,     # O2
    'EX_cpd00149_e0': 100.0,     # Co2+
    'EX_cpd00058_e0': 100.0,     # Cu2+
    'EX_cpd00067_e0': 1.0,       # H+
    'EX_cpd00030_e0': 100.0,     # Mn2
    'EX_cpd00034_e0': 100.0,     # Zn2
    'EX_cpd00048_e0': 100.0,     # Sulfate
}

data = {
    'reaction': [
        'EX_cpd00063_e0', 'EX_cpd00099_e0', 'EX_cpd00137_e0', 'EX_cpd00009_e0', 
        'EX_cpd00205_e0', 'EX_cpd11632_e0', 'EX_cpd00254_e0', 'EX_cpd10516_e0', 
        'EX_cpd00013_e0', 'EX_cpd00007_e0', 'EX_cpd00149_e0', 'EX_cpd00058_e0', 
        'EX_cpd00067_e0', 'EX_cpd00030_e0', 'EX_cpd00034_e0', 'EX_cpd00048_e0'
    ],
    'flux': [
        100.0, 100.0, 5.0, 100.0, 
        100.0, 100.0, 100.0, 1.0, 
        100.0, 100.0, 100.0, 100.0, 
        1.0, 100.0, 100.0, 100.0
    ],
    'metabolite': [
        'Ca+', 'Cl-', 'Citrate', 'Phosphate', 
        'K+', 'Photon', 'Mg', 'Fe3+', 
        'Ammonium', 'O2', 'Co2+', 'Cu2+', 
        'H+', 'Mn2', 'Zn2', 'Sulfate'
    ]
}

df_medium = pd.DataFrame(data)

In [3]:
# ----------------------------
# Configure Logging
# ----------------------------

# First, get the root logger
logger = logging.getLogger()
logger.setLevel(logging.INFO)  # Set the desired logging level

# Remove any existing handlers to prevent duplicate logs
if logger.hasHandlers():
    logger.handlers.clear()

# Create a file handler to save logs to a file
file_handler = logging.FileHandler('model_processing.log')
file_handler.setLevel(logging.INFO)

# Create a stream handler to print logs to the Jupyter cell
stream_handler = logging.StreamHandler()
stream_handler.setLevel(logging.INFO)

# Define a common formatter
formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')

# Assign the formatter to both handlers
file_handler.setFormatter(formatter)
stream_handler.setFormatter(formatter)

# Add both handlers to the logger
logger.addHandler(file_handler)
logger.addHandler(stream_handler)



def adjust_medium(model, medium):
    """
    Adjust the medium for the given model based on available exchange reactions.
    """
    adjusted_medium = {}
    available_exchanges = {rxn.id for rxn in model.exchanges}
    for rxn_id, value in medium.items():
        if rxn_id in available_exchanges:
            adjusted_medium[rxn_id] = value
        else:
            logging.warning(f"Exchange reaction {rxn_id} not found in model {model.id}")
    return adjusted_medium

def add_exchange_reaction(model, metabolite_id_base, lower_bound=-1000, upper_bound=1000):
    """
    Adds an exchange reaction for a metabolite, creating external and transport reactions if necessary.
    """
    # Build metabolite IDs
    internal_met_id = f"M_{metabolite_id_base}_c0"
    external_met_id = f"M_{metabolite_id_base}_e0"
    exchange_rxn_id = f"EX_M_{metabolite_id_base}_e0"
    transport_rxn_id = f"TRANS_M_{metabolite_id_base}"
    
    # Check if the internal metabolite exists
    try:
        internal_met = model.metabolites.get_by_id(internal_met_id)
    except KeyError:
        logging.error(f"Internal metabolite {internal_met_id} not found in model {model.id}. Cannot proceed.")
        return
    
    # Check if the external metabolite exists; if not, create it
    external_met = model.metabolites.get_by_id(external_met_id, None)
    if external_met is None:
        external_met = Metabolite(
            id=external_met_id,
            formula=internal_met.formula,
            name=internal_met.name,
            compartment='e0'
        )
        model.add_metabolites([external_met])
        logging.info(f"Added external metabolite {external_met_id} to model {model.id}")
    
    # Add the transport reaction if it doesn't exist
    if transport_rxn_id not in model.reactions:
        transport_rxn = Reaction(id=transport_rxn_id)
        transport_rxn.name = f"Transport of {internal_met.name}"
        transport_rxn.lower_bound = -1000
        transport_rxn.upper_bound = 1000
        transport_rxn.add_metabolites({internal_met: -1, external_met: 1})
        model.add_reactions([transport_rxn])
        logging.info(f"Added transport reaction {transport_rxn_id} to model {model.id}")
    
    # Add the exchange reaction if it doesn't exist
    if exchange_rxn_id not in model.reactions:
        exchange_rxn = Reaction(id=exchange_rxn_id)
        exchange_rxn.name = f"Exchange of {external_met.name}"
        exchange_rxn.lower_bound = lower_bound
        exchange_rxn.upper_bound = upper_bound
        exchange_rxn.add_metabolites({external_met: -1})
        model.add_reactions([exchange_rxn])
        logging.info(f"Added exchange reaction {exchange_rxn_id} to model {model.id}")
    else:
        logging.info(f"Exchange reaction {exchange_rxn_id} already exists in model {model.id}")

def add_all_exchange_reactions(model, medium):
    """
    Add exchange reactions for all components defined in the medium.
    """
    for rxn_id in medium.keys():
        if rxn_id not in model.reactions:
            # Infer metabolite ID by removing 'EX_' prefix
            if rxn_id.startswith('EX_'):
                metabolite_id = rxn_id[3:]
                if metabolite_id in model.metabolites:
                    add_exchange_reaction(model, metabolite_id, reaction_id=rxn_id)
                else:
                    logging.warning(f"Metabolite {metabolite_id} corresponding to {rxn_id} not found in model {model.id}. Exchange reaction {rxn_id} not added.")
            else:
                logging.warning(f"Reaction ID {rxn_id} does not follow the 'EX_' prefix convention. Skipping.")

def process_model(model_path, output_dir, medium):
    """
    Load a model, adjust it by adding exchange reactions for all medium components,
    set the medium, optimize the model, and save the adjusted model to the output directory.
    """
    try:
        # Load the model using micom.util.load_model (keeping it as is)
        model = micom.util.load_model(str(model_path))
        logging.info(f"\nProcessing model: {model.id}")

        # Add exchange reactions for all medium components
        add_all_exchange_reactions(model, medium)

        # Adjust the medium
        adjusted_medium = adjust_medium(model, medium)
        model.medium = adjusted_medium

        # Optional: Optimize the model to ensure it can grow
        solution = model.optimize()
        logging.info(f"Model {model.id} growth rate after adjustment: {solution.objective_value}")

        # Save the adjusted model using the existing save function
        output_model_path = output_dir / model_path.name
        write_sbml_model(model, output_model_path)  # Keeping the saving function as is
        logging.info(f"Saved adjusted model to {output_model_path}")

    except Exception as e:
        logging.error(f"Failed to process model {model_path.name}: {e}")


"""
Main function to process all models in the specified directory.
"""
# Iterate through all files in the model_db_path
for model_file in model_db_path.iterdir():
    # Check if the file is an XML file (common format for metabolic models)
    if model_file.suffix.lower() in ['.xml']:
        process_model(model_file, adjusted_models_path, medium)
    else:
        logging.warning(f"Skipping unsupported file format: {model_file.name}")

logging.info("\nAll models have been processed.")

# ----------------------------
# Copy Manifest File to the Output Directory
# ----------------------------

# Define the manifest file name (adjust if your manifest file has a different name)
manifest_filename = "manifest.csv"  # Replace with the actual manifest file name if different

# Define the source and destination paths for the manifest file
source_manifest = model_db_path / manifest_filename
destination_manifest = adjusted_models_path / manifest_filename

# Check if the manifest file exists in the source directory
if source_manifest.exists():
    try:
        shutil.copy2(source_manifest, destination_manifest)
        logging.info(f"Copied manifest file to {destination_manifest}")
    except Exception as e:
        logging.error(f"Failed to copy manifest file: {e}")
else:
    logging.warning(f"Manifest file {manifest_filename} not found in {model_db_path}. No manifest copied.")

2025-10-02 16:48:38,982 - INFO - reading model from models/bin.2.xml
2025-10-02 16:48:42,184 - INFO -
Processing model: bin_2
2025-10-02 16:48:42,195 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2025-10-02 16:48:42,209 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2025-10-02 16:48:42,307 - INFO - Model bin_2 growth rate after adjustment: 0.313354579139377
2025-10-02 16:48:43,957 - INFO - Saved adjusted model to adjusted_models/bin.2.xml
2025-10-02 16:48:44,038 - INFO - reading model from models/bin.3.xml
2025-10-02 16:48:48,251 - INFO -
Processing model: bin_3
2025-10-02 16:48:48,260 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2025-10-02 16:48:48,280 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2025-10-02 16:48:48,397 - INFO - Model bin_3 growth rate after adjustment: 0.3492897771712656
2025-10-02 16:48:50,550 - INFO - Saved adjusted model to adjusted_models/bin.3.xml
2025-10-02 16:48:50,578 - INFO - reading model from models/bin.4.xml
2025-10-02 16:48:53,667 - INFO -
Processing model: bin_4
2025-10-02 16:48:53,675 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2025-10-02 16:48:53,687 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2025-10-02 16:48:53,773 - INFO - Model bin_4 growth rate after adjustment: 0.24000709526070624
2025-10-02 16:48:55,307 - INFO - Saved adjusted model to adjusted_models/bin.4.xml
2025-10-02 16:48:55,310 - INFO - reading model from models/bin.1.xml
2025-10-02 16:48:58,456 - INFO -
Processing model: bin_1
2025-10-02 16:48:58,469 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2025-10-02 16:48:58,481 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2025-10-02 16:48:58,566 - INFO - Model bin_1 growth rate after adjustment: 0.1314082146053435
2025-10-02 16:49:00,209 - INFO - Saved adjusted model to adjusted_models/bin.1.xml
2025-10-02 16:49:00,237 - INFO - reading model from models/bin.7.xml
2025-10-02 16:49:03,014 - INFO -
Processing model: bin_7
2025-10-02 16:49:03,023 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2025-10-02 16:49:03,035 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2025-10-02 16:49:03,115 - INFO - Model bin_7 growth rate after adjustment: 0.6615918474040569
2025-10-02 16:49:04,570 - INFO - Saved adjusted model to adjusted_models/bin.7.xml
2025-10-02 16:49:04,573 - INFO - reading model from models/bin.8.xml
2025-10-02 16:49:06,277 - INFO -
Processing model: bin_8
2025-10-02 16:49:06,284 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2025-10-02 16:49:06,293 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2025-10-02 16:49:06,338 - INFO - Model bin_8 growth rate after adjustment: 0.12335810382321463
2025-10-02 16:49:07,183 - INFO - Saved adjusted model to adjusted_models/bin.8.xml
2025-10-02 16:49:07,220 - INFO - reading model from models/bin.5.xml
2025-10-02 16:49:09,881 - INFO -
Processing model: bin_5
2025-10-02 16:49:09,891 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2025-10-02 16:49:09,902 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2025-10-02 16:49:09,979 - INFO - Model bin_5 growth rate after adjustment: 0.12080706756694355
2025-10-02 16:49:11,369 - INFO - Saved adjusted model to adjusted_models/bin.5.xml
2025-10-02 16:49:11,373 - INFO - reading model from models/bin.6.xml
2025-10-02 16:49:14,129 - INFO -
Processing model: bin_6
2025-10-02 16:49:14,140 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2025-10-02 16:49:14,152 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2025-10-02 16:49:14,228 - INFO - Model bin_6 growth rate after adjustment: 0.4304750602452729
2025-10-02 16:49:15,644 - INFO - Saved adjusted model to adjusted_models/bin.6.xml
2025-10-02 16:49:15,649 - WARNING - Skipping unsupported file format: manifest.csv
2025-10-02 16:49:15,651 - INFO -
All models have been processed.
2025-10-02 16:49:15,654 - INFO - Copied manifest file to adjusted_models/manifest.csv

In [4]:
manifest = pd.read_csv(model_db_path / "manifest.csv")
manifest.head(10)

,id,file,domain,phylum,class,order,family,genus,species,summary_rank
0,bin.1,bin.1.xml,Bacteria,Proteobacteria,Alphaproteobacteria,Caulobacterales,Caulobacteraceae,Caulobacter,NaN,genus
1,bin.2,bin.2.xml,Bacteria,Proteobacteria,Gammaproteobacteria,Burkholderiales,Burkholderiaceae,Limnobacter,sp002954425,genus
2,bin.3,bin.3.xml,Bacteria,Proteobacteria,Gammaproteobacteria,Burkholderiales,Burkholderiaceae,Hydrogenophaga,NaN,genus
3,bin.4,bin.4.xml,Bacteria,Bacteroidota,Bacteroidia,Chitinophagales,Chitinophagaceae,Phnomibacter,NaN,genus
4,bin.5,bin.5.xml,Bacteria,Bacteroidota,Bacteroidia,Chitinophagales,Chitinophagaceae,Sediminibacterium,NaN,genus
5,bin.6,bin.6.xml,Bacteria,Bacteroidota,Bacteroidia,NS11-12g,UBA8524,SB11,sp008933805,genus
6,bin.7,bin.7.xml,Bacteria,Cyanobacteria,Cyanobacteriia,Cyanobacteriales,Aphanizomenonaceae,Aphanizomenon,flos-aquae,genus
7,bin.8,bin.8.xml,Bacteria,Proteobacteria,Alphaproteobacteria,Sphingomonadales,Sphingomonadaceae,Sphingorhabdus_B,NaN,genus

In [5]:
from micom.workflows import build
taxonomy = pd.DataFrame({
    'id': ['bin.1', 'bin.2', 'bin.3', 'bin.4','bin.5', 'bin.6', 'bin.7', 'bin.8'],
    'sample_id': ['sample_1', 'sample_1', 'sample_1', 'sample_1','sample_1', 'sample_1', 'sample_1', 'sample_1'],
    'abundance': [0.125, 0.125,0.125,0.125,0.125,0.125,0.125,0.125],
    'phylum': ['Proteobacteria', 'Proteobacteria', 'Proteobacteria', 'Bacteroidota', 'Bacteroidota', 'Bacteroidota', 'Cyanobacteria', 'Proteobacteria'],
    'file': [
    'adjusted_models/bin.1.xml', 
    'adjusted_models/bin.2.xml', 
    'adjusted_models/bin.3.xml', 
    'adjusted_models/bin.4.xml', 
    'adjusted_models/bin.5.xml', 
    'adjusted_models/bin.6.xml', 
    'adjusted_models/bin.7.xml', 
    'adjusted_models/bin.8.xml'
]})

# Create the community model
community = Community(taxonomy)

2025-10-02 16:49:15,693 - INFO - building new micom model None.
2025-10-02 16:49:15,694 - INFO - using the cplex solver.
2025-10-02 16:49:15,696 - INFO - 0 individuals with abundances below threshold

Output()

2025-10-02 16:49:15,776 - INFO - reading model from adjusted_models/bin.1.xml
2025-10-02 16:49:19,023 - INFO - converting IDs for bin_1
2025-10-02 16:49:19,034 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2025-10-02 16:49:19,039 - INFO - Identified e0 as the external compartment for bin_1. If that is wrong you may be in trouble...
2025-10-02 16:49:21,526 - INFO - adding reactions for bin_1 to community
2025-10-02 16:49:22,591 - INFO - adding metabolite cpd00009_m to external medium
2025-10-02 16:49:22,594 - INFO - adding metabolite cpd00023_m to external medium
2025-10-02 16:49:22,596 - INFO - adding metabolite cpd00027_m to external medium
2025-10-02 16:49:22,599 - INFO - adding metabolite cpd00028_m to external medium
2025-10-02 16:49:22,601 - INFO - adding metabolite cpd00034_m to external medium
2025-10-02 16:49:22,604 - INFO - adding metabolite cpd00039_m to external medium
2025-10-02 16:49:22,606 - INFO - adding metabolite cpd00041_m to external medium
2025-10-02 16:49:22,609 - INFO - adding metabolite cpd00048_m to external medium
2025-10-02 16:49:22,611 - INFO - adding metabolite cpd00051_m to external medium
2025-10-02 16:49:22,614 - INFO - adding metabolite cpd00053_m to external medium
2025-10-02 16:49:22,616 - INFO - adding metabolite cpd00064_m to external medium
2025-10-02 16:49:22,618 - INFO - adding metabolite cpd00118_m to external medium
2025-10-02 16:49:22,620 - INFO - adding metabolite cpd00119_m to external medium
2025-10-02 16:49:22,621 - INFO - adding metabolite cpd00129_m to external medium
2025-10-02 16:49:22,623 - INFO - adding metabolite cpd00149_m to external medium
2025-10-02 16:49:22,625 - INFO - adding metabolite cpd00156_m to external medium
2025-10-02 16:49:22,628 - INFO - adding metabolite cpd00161_m to external medium
2025-10-02 16:49:22,630 - INFO - adding metabolite cpd00179_m to external medium
2025-10-02 16:49:22,632 - INFO - adding metabolite cpd00244_m to external medium
2025-10-02 16:49:22,635 - INFO - adding metabolite cpd00264_m to external medium
2025-10-02 16:49:22,637 - INFO - adding metabolite cpd00268_m to external medium
2025-10-02 16:49:22,639 - INFO - adding metabolite cpd00266_m to external medium
2025-10-02 16:49:22,642 - INFO - adding metabolite cpd00540_m to external medium
2025-10-02 16:49:22,645 - INFO - adding metabolite cpd08305_m to external medium
2025-10-02 16:49:22,647 - INFO - adding metabolite cpd10516_m to external medium
2025-10-02 16:49:22,649 - INFO - adding metabolite cpd00130_m to external medium
2025-10-02 16:49:22,652 - INFO - adding metabolite cpd00971_m to external medium
2025-10-02 16:49:22,654 - INFO - adding metabolite cpd00067_m to external medium
2025-10-02 16:49:22,657 - INFO - adding metabolite cpd00137_m to external medium
2025-10-02 16:49:22,659 - INFO - adding metabolite cpd00084_m to external medium
2025-10-02 16:49:22,662 - INFO - adding metabolite cpd00013_m to external medium
2025-10-02 16:49:22,668 - INFO - adding metabolite cpd00020_m to external medium
2025-10-02 16:49:22,672 - INFO - adding metabolite cpd00139_m to external medium
2025-10-02 16:49:22,674 - INFO - adding metabolite cpd00029_m to external medium
2025-10-02 16:49:22,677 - INFO - adding metabolite cpd00024_m to external medium
2025-10-02 16:49:22,679 - INFO - adding metabolite cpd00224_m to external medium
2025-10-02 16:49:22,682 - INFO - adding metabolite cpd00063_m to external medium
2025-10-02 16:49:22,684 - INFO - adding metabolite cpd11595_m to external medium
2025-10-02 16:49:22,687 - INFO - adding metabolite cpd10515_m to external medium
2025-10-02 16:49:22,689 - INFO - adding metabolite cpd00047_m to external medium
2025-10-02 16:49:22,692 - INFO - adding metabolite cpd00106_m to external medium
2025-10-02 16:49:22,694 - INFO - adding metabolite cpd00108_m to external medium
2025-10-02 16:49:22,696 - INFO - adding metabolite cpd00164_m to external medium
2025-10-02 16:49:22,697 - INFO - adding metabolite cpd00100_m to external medium
2025-10-02 16:49:22,699 - INFO - adding metabolite cpd00033_m to external medium
2025-10-02 16:49:22,701 - INFO - adding metabolite cpd00205_m to external medium
2025-10-02 16:49:22,703 - INFO - adding metabolite cpd00159_m to external medium
2025-10-02 16:49:22,706 - INFO - adding metabolite cpd01262_m to external medium
2025-10-02 16:49:22,708 - INFO - adding metabolite cpd11574_m to external medium
2025-10-02 16:49:22,711 - INFO - adding metabolite cpd00075_m to external medium
2025-10-02 16:49:22,713 - INFO - adding metabolite cpd00209_m to external medium
2025-10-02 16:49:22,716 - INFO - adding metabolite cpd00396_m to external medium
2025-10-02 16:49:22,718 - INFO - adding metabolite cpd01030_m to external medium
2025-10-02 16:49:22,720 - INFO - adding metabolite cpd00036_m to external medium
2025-10-02 16:49:22,723 - INFO - adding metabolite cpd00280_m to external medium
2025-10-02 16:49:22,725 - INFO - adding metabolite cpd00035_m to external medium
2025-10-02 16:49:22,727 - INFO - adding metabolite cpd00132_m to external medium
2025-10-02 16:49:22,730 - INFO - adding metabolite cpd01012_m to external medium
2025-10-02 16:49:22,732 - INFO - adding metabolite cpd00099_m to external medium
2025-10-02 16:49:22,735 - INFO - adding metabolite cpd00058_m to external medium
2025-10-02 16:49:22,737 - INFO - adding metabolite cpd00221_m to external medium
2025-10-02 16:49:22,739 - INFO - adding metabolite cpd01107_m to external medium
2025-10-02 16:49:22,742 - INFO - adding metabolite cpd01741_m to external medium
2025-10-02 16:49:22,744 - INFO - adding metabolite cpd03847_m to external medium
2025-10-02 16:49:22,747 - INFO - adding metabolite cpd15298_m to external medium
2025-10-02 16:49:22,749 - INFO - adding metabolite cpd00214_m to external medium
2025-10-02 16:49:22,751 - INFO - adding metabolite cpd15237_m to external medium
2025-10-02 16:49:22,754 - INFO - adding metabolite cpd01080_m to external medium
2025-10-02 16:49:22,756 - INFO - adding metabolite cpd15269_m to external medium
2025-10-02 16:49:22,759 - INFO - adding metabolite cpd01113_m to external medium
2025-10-02 16:49:22,761 - INFO - adding metabolite cpd03846_m to external medium
2025-10-02 16:49:22,763 - INFO - adding metabolite cpd00254_m to external medium
2025-10-02 16:49:22,766 - INFO - adding metabolite cpd00305_m to external medium
2025-10-02 16:49:22,768 - INFO - adding metabolite cpd00082_m to external medium
2025-10-02 16:49:22,771 - INFO - adding metabolite cpd00010_m to external medium
2025-10-02 16:49:22,777 - INFO - adding metabolite cpd00054_m to external medium
2025-10-02 16:49:22,781 - INFO - adding metabolite cpd00133_m to external medium
2025-10-02 16:49:22,784 - INFO - adding metabolite cpd00153_m to external medium
2025-10-02 16:49:22,787 - INFO - adding metabolite cpd00210_m to external medium
2025-10-02 16:49:22,789 - INFO - adding metabolite cpd00380_m to external medium
2025-10-02 16:49:22,792 - INFO - adding metabolite cpd00185_m to external medium
2025-10-02 16:49:22,795 - INFO - adding metabolite cpd00152_m to external medium
2025-10-02 16:49:22,797 - INFO - adding metabolite cpd00006_m to external medium
2025-10-02 16:49:22,800 - INFO - adding metabolite cpd00138_m to external medium
2025-10-02 16:49:22,802 - INFO - adding metabolite cpd00180_m to external medium
2025-10-02 16:49:22,805 - INFO - adding metabolite cpd00038_m to external medium
2025-10-02 16:49:22,807 - INFO - adding metabolite cpd02733_m to external medium
2025-10-02 16:49:22,809 - INFO - adding metabolite cpd00001_m to external medium
2025-10-02 16:49:22,812 - INFO - adding metabolite cpd00011_m to external medium
2025-10-02 16:49:22,814 - INFO - adding metabolite cpd00007_m to external medium
2025-10-02 16:49:22,817 - INFO - adding metabolite cpd01981_m to external medium
2025-10-02 16:49:22,820 - INFO - adding metabolite cpd00141_m to external medium
2025-10-02 16:49:22,822 - INFO - adding metabolite cpd00073_m to external medium
2025-10-02 16:49:22,824 - INFO - adding metabolite cpd01861_m to external medium
2025-10-02 16:49:22,826 - INFO - adding metabolite cpd00453_m to external medium
2025-10-02 16:49:22,828 - INFO - adding metabolite cpd00071_m to external medium
2025-10-02 16:49:22,830 - INFO - adding metabolite cpd00150_m to external medium
2025-10-02 16:49:22,831 - INFO - adding metabolite cpd08021_m to external medium
2025-10-02 16:49:22,833 - INFO - adding metabolite cpd00450_m to external medium
2025-10-02 16:49:22,836 - INFO - adding metabolite cpd00363_m to external medium
2025-10-02 16:49:22,839 - INFO - adding metabolite cpd00055_m to external medium
2025-10-02 16:49:22,841 - INFO - adding metabolite cpd00448_m to external medium
2025-10-02 16:49:22,844 - INFO - adding metabolite cpd00025_m to external medium
2025-10-02 16:49:22,845 - INFO - adding metabolite cpd00239_m to external medium
2025-10-02 16:49:22,847 - INFO - adding metabolite cpd11640_m to external medium
2025-10-02 16:49:22,849 - INFO - adding metabolite cpd00359_m to external medium
2025-10-02 16:49:22,850 - INFO - adding metabolite cpd00659_m to external medium
2025-10-02 16:49:22,853 - INFO - adding metabolite cpd00418_m to external medium
2025-10-02 16:49:22,856 - INFO - adding metabolite cpd00371_m to external medium
2025-10-02 16:49:22,858 - INFO - adding metabolite cpd00811_m to external medium
2025-10-02 16:49:22,861 - INFO - adding metabolite cpd00324_m to external medium
2025-10-02 16:49:22,863 - INFO - adding metabolite cpd01024_m to external medium
2025-10-02 16:49:22,866 - INFO - adding metabolite cpd00204_m to external medium
2025-10-02 16:49:22,868 - INFO - adding metabolite cpd00116_m to external medium
2025-10-02 16:49:22,870 - INFO - adding metabolite cpd00528_m to external medium
2025-10-02 16:49:22,873 - INFO - adding metabolite cpd11632_m to external medium
2025-10-02 16:49:22,876 - INFO - adding metabolite cpd03662_m to external medium
2025-10-02 16:49:22,883 - INFO - adding metabolite cpd00178_m to external medium
2025-10-02 16:49:22,885 - INFO - adding metabolite cpd01618_m to external medium
2025-10-02 16:49:22,888 - INFO - adding metabolite cpd00030_m to external medium
2025-10-02 16:49:22,892 - INFO - adding metabolite cpd11451_m to external medium
2025-10-02 16:49:22,895 - INFO - adding metabolite cpd11606_m to external medium
2025-10-02 16:49:22,897 - INFO - adding metabolite cpd00121_m to external medium
2025-10-02 16:49:22,900 - INFO - adding metabolite cpd00314_m to external medium
2025-10-02 16:49:22,902 - INFO - adding metabolite cpd00588_m to external medium
2025-10-02 16:49:22,904 - INFO - adding metabolite cpd00322_m to external medium
2025-10-02 16:49:22,906 - INFO - adding metabolite cpd00107_m to external medium
2025-10-02 16:49:22,907 - INFO - adding metabolite cpd00060_m to external medium
2025-10-02 16:49:22,909 - INFO - adding metabolite cpd00066_m to external medium
2025-10-02 16:49:22,911 - INFO - adding metabolite cpd00065_m to external medium
2025-10-02 16:49:22,914 - INFO - adding metabolite cpd00069_m to external medium
2025-10-02 16:49:22,916 - INFO - adding metabolite cpd00249_m to external medium
2025-10-02 16:49:22,918 - INFO - adding metabolite cpd00276_m to external medium
2025-10-02 16:49:22,921 - INFO - adding metabolite cpd00366_m to external medium
2025-10-02 16:49:22,923 - INFO - adding metabolite cpd00222_m to external medium
2025-10-02 16:49:22,926 - INFO - adding metabolite cpd00105_m to external medium
2025-10-02 16:49:22,928 - INFO - adding metabolite cpd00154_m to external medium
2025-10-02 16:49:22,931 - INFO - adding metabolite cpd00003_m to external medium
2025-10-02 16:49:22,933 - INFO - adding metabolite cpd00017_m to external medium
2025-10-02 16:49:22,936 - INFO - adding metabolite cpd00098_m to external medium
2025-10-02 16:49:22,938 - INFO - adding metabolite cpd00117_m to external medium
2025-10-02 16:49:22,941 - INFO - adding metabolite cpd00220_m to external medium
2025-10-02 16:49:22,944 - INFO - adding metabolite cpd00277_m to external medium
2025-10-02 16:49:22,946 - INFO - adding metabolite cpd00281_m to external medium
2025-10-02 16:49:22,949 - INFO - adding metabolite cpd00367_m to external medium
2025-10-02 16:49:22,951 - INFO - adding metabolite cpd00550_m to external medium
2025-10-02 16:49:22,954 - INFO - adding metabolite cpd00644_m to external medium
2025-10-02 16:49:22,956 - INFO - adding metabolite cpd00653_m to external medium
2025-10-02 16:49:22,959 - INFO - reading model from adjusted_models/bin.2.xml
2025-10-02 16:49:26,237 - INFO - converting IDs for bin_2
2025-10-02 16:49:26,247 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2025-10-02 16:49:26,252 - INFO - Identified e0 as the external compartment for bin_2. If that is wrong you may be in trouble...
2025-10-02 16:49:28,423 - INFO - adding reactions for bin_2 to community
2025-10-02 16:49:29,329 - INFO - updating import rate for external metabolite cpd00009_m
2025-10-02 16:49:29,332 - INFO - updating import rate for external metabolite cpd00023_m
2025-10-02 16:49:29,334 - INFO - updating import rate for external metabolite cpd00027_m
2025-10-02 16:49:29,335 - INFO - updating import rate for external metabolite cpd00028_m
2025-10-02 16:49:29,337 - INFO - updating import rate for external metabolite cpd00030_m
2025-10-02 16:49:29,338 - INFO - updating import rate for external metabolite cpd00039_m
2025-10-02 16:49:29,340 - INFO - updating import rate for external metabolite cpd00041_m
2025-10-02 16:49:29,342 - INFO - updating import rate for external metabolite cpd00048_m
2025-10-02 16:49:29,344 - INFO - updating import rate for external metabolite cpd00051_m
2025-10-02 16:49:29,346 - INFO - updating import rate for external metabolite cpd00053_m
2025-10-02 16:49:29,349 - INFO - updating import rate for external metabolite cpd00064_m
2025-10-02 16:49:29,351 - INFO - updating import rate for external metabolite cpd00073_m
2025-10-02 16:49:29,353 - INFO - updating import rate for external metabolite cpd00107_m
2025-10-02 16:49:29,354 - INFO - updating import rate for external metabolite cpd00108_m
2025-10-02 16:49:29,356 - INFO - updating import rate for external metabolite cpd00118_m
2025-10-02 16:49:29,358 - INFO - updating import rate for external metabolite cpd00119_m
2025-10-02 16:49:29,360 - INFO - updating import rate for external metabolite cpd00129_m
2025-10-02 16:49:29,362 - INFO - updating import rate for external metabolite cpd00149_m
2025-10-02 16:49:29,364 - INFO - updating import rate for external metabolite cpd00154_m
2025-10-02 16:49:29,366 - INFO - updating import rate for external metabolite cpd00156_m
2025-10-02 16:49:29,369 - INFO - updating import rate for external metabolite cpd00161_m
2025-10-02 16:49:29,371 - INFO - updating import rate for external metabolite cpd00179_m
2025-10-02 16:49:29,373 - INFO - updating import rate for external metabolite cpd00209_m
2025-10-02 16:49:29,375 - INFO - updating import rate for external metabolite cpd00210_m
2025-10-02 16:49:29,377 - INFO - updating import rate for external metabolite cpd00224_m
2025-10-02 16:49:29,379 - INFO - updating import rate for external metabolite cpd00244_m
2025-10-02 16:49:29,381 - INFO - updating import rate for external metabolite cpd00264_m
2025-10-02 16:49:29,383 - INFO - updating import rate for external metabolite cpd00268_m
2025-10-02 16:49:29,385 - INFO - updating import rate for external metabolite cpd00322_m
2025-10-02 16:49:29,388 - INFO - adding metabolite cpd03724_m to external medium
2025-10-02 16:49:29,391 - INFO - updating import rate for external metabolite cpd10516_m
2025-10-02 16:49:29,393 - INFO - updating import rate for external metabolite cpd00067_m
2025-10-02 16:49:29,396 - INFO - updating import rate for external metabolite cpd00249_m
2025-10-02 16:49:29,398 - INFO - updating import rate for external metabolite cpd00130_m
2025-10-02 16:49:29,400 - INFO - updating import rate for external metabolite cpd00971_m
2025-10-02 16:49:29,403 - INFO - updating import rate for external metabolite cpd00137_m
2025-10-02 16:49:29,405 - INFO - updating import rate for external metabolite cpd00035_m
2025-10-02 16:49:29,407 - INFO - updating import rate for external metabolite cpd00060_m
2025-10-02 16:49:29,409 - INFO - updating import rate for external metabolite cpd00084_m
2025-10-02 16:49:29,410 - INFO - updating import rate for external metabolite cpd00013_m
2025-10-02 16:49:29,413 - INFO - updating import rate for external metabolite cpd00020_m
2025-10-02 16:49:29,423 - INFO - updating import rate for external metabolite cpd00029_m
2025-10-02 16:49:29,427 - INFO - updating import rate for external metabolite cpd00132_m
2025-10-02 16:49:29,429 - INFO - updating import rate for external metabolite cpd11595_m
2025-10-02 16:49:29,431 - INFO - updating import rate for external metabolite cpd10515_m
2025-10-02 16:49:29,433 - INFO - updating import rate for external metabolite cpd00082_m
2025-10-02 16:49:29,435 - INFO - updating import rate for external metabolite cpd00106_m
2025-10-02 16:49:29,437 - INFO - updating import rate for external metabolite cpd00033_m
2025-10-02 16:49:29,439 - INFO - updating import rate for external metabolite cpd00205_m
2025-10-02 16:49:29,442 - INFO - adding metabolite cpd00208_m to external medium
2025-10-02 16:49:29,445 - INFO - updating import rate for external metabolite cpd00159_m
2025-10-02 16:49:29,447 - INFO - updating import rate for external metabolite cpd01262_m
2025-10-02 16:49:29,449 - INFO - updating import rate for external metabolite cpd11574_m
2025-10-02 16:49:29,451 - INFO - adding metabolite cpd01132_m to external medium
2025-10-02 16:49:29,453 - INFO - updating import rate for external metabolite cpd00396_m
2025-10-02 16:49:29,455 - INFO - updating import rate for external metabolite cpd00036_m
2025-10-02 16:49:29,458 - INFO - adding metabolite cpd01217_m to external medium
2025-10-02 16:49:29,461 - INFO - adding metabolite cpd00751_m to external medium
2025-10-02 16:49:29,463 - INFO - updating import rate for external metabolite cpd01012_m
2025-10-02 16:49:29,465 - INFO - updating import rate for external metabolite cpd00099_m
2025-10-02 16:49:29,467 - INFO - updating import rate for external metabolite cpd00058_m
2025-10-02 16:49:29,469 - INFO - adding metabolite cpd01015_m to external medium
2025-10-02 16:49:29,472 - INFO - updating import rate for external metabolite cpd00277_m
2025-10-02 16:49:29,474 - INFO - updating import rate for external metabolite cpd00221_m
2025-10-02 16:49:29,476 - INFO - adding metabolite cpd00412_m to external medium
2025-10-02 16:49:29,479 - INFO - updating import rate for external metabolite cpd01107_m
2025-10-02 16:49:29,481 - INFO - updating import rate for external metabolite cpd01741_m
2025-10-02 16:49:29,483 - INFO - updating import rate for external metabolite cpd03847_m
2025-10-02 16:49:29,485 - INFO - updating import rate for external metabolite cpd15298_m
2025-10-02 16:49:29,487 - INFO - updating import rate for external metabolite cpd00214_m
2025-10-02 16:49:29,489 - INFO - updating import rate for external metabolite cpd15237_m
2025-10-02 16:49:29,491 - INFO - updating import rate for external metabolite cpd01080_m
2025-10-02 16:49:29,493 - INFO - updating import rate for external metabolite cpd15269_m
2025-10-02 16:49:29,495 - INFO - updating import rate for external metabolite cpd01113_m
2025-10-02 16:49:29,497 - INFO - updating import rate for external metabolite cpd03846_m
2025-10-02 16:49:29,499 - INFO - adding metabolite cpd03587_m to external medium
2025-10-02 16:49:29,501 - INFO - updating import rate for external metabolite cpd00254_m
2025-10-02 16:49:29,504 - INFO - updating import rate for external metabolite cpd00034_m
2025-10-02 16:49:29,506 - INFO - updating import rate for external metabolite cpd00305_m
2025-10-02 16:49:29,508 - INFO - adding metabolite cpd04097_m to external medium

In [6]:
manifest = build(taxonomy, model_db=None, out_folder="community_models") 
manifest.head(10)

[10/02/25 16:50:08] WARNING  Found existing models for 1 samples. Will skip those. Delete the output    ]8;id=639953;file:///mnt/workspace/miniconda3/envs/micom/lib/python3.9/site-packages/micom/workflows/build.py\build.py]8;;\:]8;id=397964;file:///mnt/workspace/miniconda3/envs/micom/lib/python3.9/site-packages/micom/workflows/build.py#98\98]8;;\
                             folder if you would like me to rebuild them.

2025-10-02 16:50:08,955 - WARNING - Found existing models for 1 samples. Will skip those. Delete the output folder if you would like me to rebuild them.

Output()

  sample_id  abundance             file
0  sample_1      0.125  sample_1.pickle

In [7]:

#rename medium compounds for comunity
def transform_medium(medium_dict):
    """
    Transforms the keys of the medium dictionary from 'EX_cpdXXXXX_e0' to 'cpdXXXXX_m'.

    Parameters:
    - medium_dict (dict): Original medium dictionary with keys like 'EX_cpdXXXXX_e0'.

    Returns:
    - dict: New dictionary with keys transformed to 'cpdXXXXX_m'.
    """
    transformed_dict = {}
    for key, value in medium_dict.items():
        if key.startswith('EX_') and key.endswith('_e0'):
            compound_id = key[3:-3]  # Extract 'cpdXXXXX' from 'EX_cpdXXXXX_e0'
            new_key = f"EX_{compound_id}_m"  # Form the new key 'cpdXXXXX_m'
            transformed_dict[new_key] = value
        else:
            # Handle keys that don't match the expected format
            transformed_dict[key] = value
    return transformed_dict
medium4com = transform_medium(medium)
medium_df = pd.DataFrame(transform_medium(medium).items(), columns=['reaction', 'flux'])

In [8]:
medium_df

         reaction   flux
0   EX_cpd00063_m  100.0
1   EX_cpd00099_m  100.0
2   EX_cpd00137_m    5.0
3   EX_cpd00009_m  100.0
4   EX_cpd00205_m  100.0
5   EX_cpd11632_m  100.0
6   EX_cpd00254_m  100.0
7   EX_cpd10516_m    1.0
8   EX_cpd00013_m  100.0
9   EX_cpd00007_m  100.0
10  EX_cpd00149_m  100.0
11  EX_cpd00058_m  100.0
12  EX_cpd00067_m    1.0
13  EX_cpd00030_m  100.0
14  EX_cpd00034_m  100.0
15  EX_cpd00048_m  100.0

In [9]:
from micom.workflows import tradeoff

tradeoff_rates = tradeoff(manifest, model_folder="community_models", medium=medium_df, threads=2)
tradeoff_rates.head()

Output()

,abundance,growth_rate,reactions,metabolites,taxon,tradeoff,sample_id
compartments,,,,,,,
bin_1,0.125,0.000000,1867,1781,bin_1,NaN,sample_1
bin_2,0.125,0.000000,1836,1712,bin_2,NaN,sample_1
bin_3,0.125,0.000000,2353,2046,bin_3,NaN,sample_1
bin_4,0.125,1.343744,1840,1588,bin_4,NaN,sample_1
bin_5,0.125,0.620673,1623,1432,bin_5,NaN,sample_1

In [10]:
tradeoff_rates.groupby("tradeoff").apply(
    lambda df: (df.growth_rate > 1e-6).sum()).reset_index()

/tmp/ipykernel_891476/957046585.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tradeoff_rates.groupby("tradeoff").apply(

   tradeoff  0
0       0.1  8
1       0.2  8
2       0.3  8
3       0.4  8
4       0.5  8
5       0.6  8
6       0.7  8
7       0.8  8
8       0.9  8
9       1.0  8

In [11]:
from micom.viz import plot_tradeoff

pl = plot_tradeoff(tradeoff_rates, filename="tradeoff.html")

2025-10-02 16:50:27,106 - INFO - Writing visualization to tradeoff.html.

In [12]:
from micom.workflows import grow
res = grow(manifest, model_folder="community_models", medium=medium_df, tradeoff=0.9, threads=2)

Output()

In [13]:
from micom.viz import plot_growth

pl = plot_growth(res, filename="growth_rates.html")
pl.view()

2025-10-02 16:50:35,272 - INFO - Writing visualization to growth_rates.html.

>4;1H84l=                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Getting file://localhost/mnt/workspace/petr/metabolic_models/wdir_afa/gapfilled

In [14]:
from micom.viz import plot_focal_interactions

pl = plot_focal_interactions(res, taxon="bin_7", filename='bin_7_interactions.html')

2025-10-02 16:50:35,934 - INFO - Writing visualization to bin_7_interactions.html.

In [15]:
from micom.interaction import MES

scores = MES(res)
scores.head()

,metabolite,sample_id,MES,name,molecular_weight,C_number,N_number,sbo,metanetx.chemical,inchikey,seed.compound,hmdb,reactome,kegg.compound,chebi,bigg.metabolite,biocyc,reaction
0,cpd00001_e0,sample_1,3.750000,H2O-e0,18.015280,0,0,SBO:0000247,MNXM2,XLYOFNOQVPJJNP-UHFFFAOYSA-N,cpd00001,"['HMDB01039', 'HMDB02111']","['R-ALL-109276', 'R-ALL-113518', 'R-ALL-113519...","['C00001', 'C01328']",CHEBI:15377,h2o,META:WATER,EX_cpd00001_e0
1,cpd00003_e0,sample_1,2.857143,NAD-e0,662.417162,21,7,SBO:0000247,MNXM8,BAWFJGJZGIEFAR-NNYOXOHSSA-M,cpd00003,HMDB00902,"['R-ALL-113526', 'R-ALL-192307', 'R-ALL-194653...",C00003,CHEBI:57540,nad,META:NAD,EX_cpd00003_e0
2,cpd00006_e0,sample_1,2.666667,NADP-e0,740.381183,21,7,SBO:0000247,MNXM5,XJLXINKUBYWONI-NNYOXOHSSA-K,cpd00006,HMDB00217,"['R-ALL-113563', 'R-ALL-113564', 'R-ALL-194668...",C00006,CHEBI:58349,nadp,META:NADP,EX_cpd00006_e0
3,cpd00007_e0,sample_1,3.000000,O2-e0,31.998800,0,0,SBO:0000247,MNXM4,MYMOFIZGZYHOMD-UHFFFAOYSA-N,cpd00007,HMDB01377,"['R-ALL-1131511', 'R-ALL-113533', 'R-ALL-11353...",C00007,CHEBI:15379,o2,META:OXYGEN-MOLECULE,EX_cpd00007_e0
4,cpd00009_e0,sample_1,0.000000,Phosphate-e0,95.979301,0,0,SBO:0000247,MNXM9,NBIIXXVUZAFLBC-UHFFFAOYSA-L,cpd00009,"['HMDB00973', 'HMDB01429', 'HMDB05947', 'HMDB0...","['R-ALL-109277', 'R-ALL-113548', 'R-ALL-113550...",C00009,CHEBI:43474,pi,"['META:CPD-16459', 'META:PHOSPHATE-GROUP', 'ME...",EX_cpd00009_e0

In [16]:

from micom.viz import plot_mes


pl = plot_mes(res, filename="mes.html")

2025-10-02 16:50:36,021 - INFO - Writing visualization to mes.html.

In [17]:
exch_df = res.exchanges
exch_df

,taxon,sample_id,tolerance,reaction,flux,abundance,metabolite,direction
0,bin_1,sample_1,0.000001,EX_cpd00130_e0,22.293177,0.125,cpd00130_e0,export
1,bin_1,sample_1,0.000001,EX_cpd00024_e0,-14.732060,0.125,cpd00024_e0,import
2,bin_1,sample_1,0.000001,EX_cpd00107_e0,-0.087801,0.125,cpd00107_e0,import
4,bin_1,sample_1,0.000001,EX_cpd00007_e0,-6.778556,0.125,cpd00007_e0,import
5,bin_1,sample_1,0.000001,EX_cpd00100_e0,4.140715,0.125,cpd00100_e0,export
...,...,...,...,...,...,...,...,...
1309,medium,sample_1,0.000001,EX_cpd00205_m,-0.003402,NaN,cpd00205_m,import
1313,medium,sample_1,0.000001,EX_cpd00013_m,-7.823702,NaN,cpd00013_m,import
1336,medium,sample_1,0.000001,EX_cpd00058_m,-0.003402,NaN,cpd00058_m,import
1345,medium,sample_1,0.000001,EX_cpd00034_m,-0.003402,NaN,cpd00034_m,import
1367,medium,sample_1,0.000001,EX_cpd00001_m,13.163844,NaN,cpd00001_m,export

In [18]:
print(res.exchanges)
bin_7_exchanges = (res.exchanges[res.exchanges.taxon == "bin_7"])

       taxon sample_id  tolerance        reaction       flux  abundance  \
0      bin_1  sample_1   0.000001  EX_cpd00130_e0  22.293177      0.125
1      bin_1  sample_1   0.000001  EX_cpd00024_e0 -14.732060      0.125
2      bin_1  sample_1   0.000001  EX_cpd00107_e0  -0.087801      0.125
4      bin_1  sample_1   0.000001  EX_cpd00007_e0  -6.778556      0.125
5      bin_1  sample_1   0.000001  EX_cpd00100_e0   4.140715      0.125
...      ...       ...        ...             ...        ...        ...
1309  medium  sample_1   0.000001   EX_cpd00205_m  -0.003402        NaN
1313  medium  sample_1   0.000001   EX_cpd00013_m  -7.823702        NaN
1336  medium  sample_1   0.000001   EX_cpd00058_m  -0.003402        NaN
1345  medium  sample_1   0.000001   EX_cpd00034_m  -0.003402        NaN
1367  medium  sample_1   0.000001   EX_cpd00001_m  13.163844        NaN

       metabolite direction
0     cpd00130_e0    export
1     cpd00024_e0    import
2     cpd00107_e0    import
4     cpd00007_e0    import
5     cpd00100_e0    export
...           ...       ...
1309   cpd00205_m    import
1313   cpd00013_m    import
1336   cpd00058_m    import
1345   cpd00034_m    import
1367   cpd00001_m    export

[600 rows x 8 columns]

In [19]:

def map_metabolite_names(df, reaction_col='reaction', new_col='metabolite_name', mapping_data=None):
    """
    Maps metabolite names to reactions in any DataFrame using a separate mapping data dictionary.

    Parameters:
        df (pd.DataFrame): The DataFrame to process.
        reaction_col (str): Name of the column in df that contains reaction codes.
        new_col (str): Name for the new column that will contain mapped metabolite names.
        mapping_data (dict): A dictionary with keys 'reaction' and 'metabolite' to build the mapping.

    Returns:
        pd.DataFrame: df with an added column for metabolite names.
    """
    if mapping_data is None or not all(k in mapping_data for k in ('reaction', 'metabolite')):
        raise ValueError("mapping_data must be a dictionary with 'reaction' and 'metabolite' keys.")

    # Build the lookup dictionary
    reaction_to_metabolite = dict(zip(mapping_data['reaction'], mapping_data['metabolite']))

    # Map and create new column
    df[new_col] = df[reaction_col].map(reaction_to_metabolite)

    return df

In [20]:
annotated_df = map_metabolite_names((res.exchanges[res.exchanges.taxon == "bin_7"]), mapping_data=data)
annotated_df

/tmp/ipykernel_891476/2953825138.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_col] = df[reaction_col].map(reaction_to_metabolite)

,taxon,sample_id,tolerance,reaction,flux,abundance,metabolite,direction,metabolite_name
926,bin_7,sample_1,0.000001,EX_cpd00130_e0,-3.107530,0.125,cpd00130_e0,import,NaN
932,bin_7,sample_1,0.000001,EX_cpd00007_e0,19.998152,0.125,cpd00007_e0,export,O2
933,bin_7,sample_1,0.000001,EX_cpd00039_e0,-0.151921,0.125,cpd00039_e0,import,NaN
934,bin_7,sample_1,0.000001,EX_cpd00220_e0,-0.003684,0.125,cpd00220_e0,import,NaN
935,bin_7,sample_1,0.000001,EX_cpd00051_e0,-0.130949,0.125,cpd00051_e0,import,NaN
939,bin_7,sample_1,0.000001,EX_cpd00036_e0,-10.417058,0.125,cpd00036_e0,import,NaN
941,bin_7,sample_1,0.000001,EX_cpd00363_e0,15.986510,0.125,cpd00363_e0,export,NaN
942,bin_7,sample_1,0.000001,EX_cpd00324_e0,-0.073556,0.125,cpd00324_e0,import,NaN
944,bin_7,sample_1,0.000001,EX_cpd00224_e0,-0.565858,0.125,cpd00224_e0,import,NaN
946,bin_7,sample_1,0.000001,EX_cpd00025_e0,0.001848,0.125,cpd00025_e0,export,NaN
947,bin_7,sample_1,0.000001,EX_cpd00149_e0,-0.003402,0.125,cpd00149_e0,import,Co2+
949,bin_7,sample_1,0.000001,EX_cpd00154_e0,0.565857,0.125,cpd00154_e0,export,NaN
950,bin_7,sample_1,0.000001,EX_cpd00161_e0,-0.159946,0.125,cpd00161_e0,import,NaN
952,bin_7,sample_1,0.000001,EX_cpd00029_e0,0.012870,0.125,cpd00029_e0,export,NaN
957,bin_7,sample_1,0.000001,EX_cpd00013_e0,-12.305115,0.125,cpd00013_e0,import,Ammonium
959,bin_7,sample_1,0.000001,EX_cpd00030_e0,-0.003402,0.125,cpd00030_e0,import,Mn2
964,bin_7,sample_1,0.000001,EX_cpd00082_e0,-0.613287,0.125,cpd00082_e0,import,NaN
965,bin_7,sample_1,0.000001,EX_cpd00071_e0,-15.986509,0.125,cpd00071_e0,import,NaN
966,bin_7,sample_1,0.000001,EX_cpd00118_e0,-0.002278,0.125,cpd00118_e0,import,NaN
968,bin_7,sample_1,0.000001,EX_cpd00011_e0,-24.862222,0.125,cpd00011_e0,import,NaN
969,bin_7,sample_1,0.000001,EX_cpd00058_e0,-0.003402,0.125,cpd00058_e0,import,Cu2+
970,bin_7,sample_1,0.000001,EX_cpd00133_e0,0.204666,0.125,cpd00133_e0,export,NaN
971,bin_7,sample_1,0.000001,EX_cpd00001_e0,-8.735985,0.125,cpd00001_e0,import,NaN
978,bin_7,sample_1,0.000001,EX_cpd00254_e0,-0.003402,0.125,cpd00254_e0,import,Mg
979,bin_7,sample_1,0.000001,EX_cpd00033_e0,-0.288292,0.125,cpd00033_e0,import,NaN
980,bin_7,sample_1,0.000001,EX_cpd10516_e0,-0.016244,0.125,cpd10516_e0,import,Fe3+
982,bin_7,sample_1,0.000001,EX_cpd00119_e0,-0.041941,0.125,cpd00119_e0,import,NaN
987,bin_7,sample_1,0.000001,EX_cpd00003_e0,-0.209086,0.125,cpd00003_e0,import,NaN
990,bin_7,sample_1,0.000001,EX_cpd00069_e0,-0.061048,0.125,cpd00069_e0,import,NaN
993,bin_7,sample_1,0.000001,EX_cpd00084_e0,-0.044239,0.125,cpd00084_e0,import,NaN
994,bin_7,sample_1,0.000001,EX_cpd11606_e0,13.894920,0.125,cpd11606_e0,export,NaN
1000,bin_7,sample_1,0.000001,EX_cpd00264_e0,-0.001403,0.125,cpd00264_e0,import,NaN
1003,bin_7,sample_1,0.000001,EX_cpd00137_e0,-11.654002,0.125,cpd00137_e0,import,Citrate
1006,bin_7,sample_1,0.000001,EX_cpd00028_e0,-0.001843,0.125,cpd00028_e0,import,NaN
1007,bin_7,sample_1,0.000001,EX_cpd11632_e0,-100.000000,0.125,cpd11632_e0,import,Photon
1008,bin_7,sample_1,0.000001,EX_cpd10515_e0,0.007600,0.125,cpd10515_e0,export,NaN
1017,bin_7,sample_1,0.000001,EX_cpd00099_e0,-0.003402,0.125,cpd00099_e0,import,Cl-
1018,bin_7,sample_1,0.000001,EX_cpd00132_e0,-0.106717,0.125,cpd00132_e0,import,NaN
1019,bin_7,sample_1,0.000001,EX_cpd11451_e0,-13.894920,0.125,cpd11451_e0,import,NaN
1020,bin_7,sample_1,0.000001,EX_cpd00041_e0,10.307266,0.125,cpd00041_e0,export,NaN
1026,bin_7,sample_1,0.000001,EX_cpd00448_e0,0.014557,0.125,cpd00448_e0,export,NaN
1027,bin_7,sample_1,0.000001,EX_cpd00065_e0,-0.025165,0.125,cpd00065_e0,import,NaN
1029,bin_7,sample_1,0.000001,EX_cpd00064_e0,0.102628,0.125,cpd00064_e0,export,NaN
1030,bin_7,sample_1,0.000001,EX_cpd00063_e0,-0.003402,0.125,cpd00063_e0,import,Ca+
1036,bin_7,sample_1,0.000001,EX_cpd11640_e0,8.095801,0.125,cpd11640_e0,export,NaN
1038,bin_7,sample_1,0.000001,EX_cpd00020_e0,9.316421,0.125,cpd00020_e0,export,NaN
1039,bin_7,sample_1,0.000001,EX_cpd00009_e0,-0.041389,0.125,cpd00009_e0,import,Phosphate
1040,bin_7,sample_1,0.000001,EX_cpd00048_e0,-0.003402,0.125,cpd00048_e0,import,Sulfate
1047,bin_7,sample_1,0.000001,EX_cpd00010_e0,-0.003683,0.125,cpd00010_e0,import,NaN
1056,bin_7,sample_1,0.000001,EX_cpd00205_e0,-0.003402,0.125,cpd00205_e0,import,K+
1059,bin_7,sample_1,0.000001,EX_cpd00034_e0,-0.003402,0.125,cpd00034_e0,import,Zn2
1061,bin_7,sample_1,0.000001,EX_cpd00047_e0,17.967516,0.125,cpd00047_e0,export,NaN
1063,bin_7,sample_1,0.000001,EX_cpd00006_e0,-0.001563,0.125,cpd00006_e0,import,NaN
1064,bin_7,sample_1,0.000001,EX_cpd00054_e0,-0.110089,0.125,cpd00054_e0,import,NaN
1065,bin_7,sample_1,0.000001,EX_cpd00067_e0,14.945746,0.125,cpd00067_e0,export,H+
1066,bin_7,sample_1,0.000001,EX_cpd00023_e0,-0.048424,0.125,cpd00023_e0,import,NaN
1067,bin_7,sample_1,0.000001,EX_cpd00106_e0,13.530820,0.125,cpd00106_e0,export,NaN
1071,bin_7,sample_1,0.000001,EX_cpd00239_e0,0.003676,0.125,cpd00239_e0,export,NaN

In [21]:
from micom.interaction import interactions

results = res
ints = interactions(results, taxa="bin_7")
ints.sort_values(by="flux", ascending=False).head()
from micom.interaction import summarize_interactions

summary = summarize_interactions(ints)
summary.head()

,sample_id,focal,partner,class,flux,mass_flux,C_flux,N_flux,n_ints
0,sample_1,bin_7,bin_1,co-consumed,4.909865,0.311760,10.770050,1.629363,28
1,sample_1,bin_7,bin_1,provided,4.741860,0.400084,16.872036,1.296470,9
2,sample_1,bin_7,bin_1,received,3.502834,0.503556,20.040289,0.075808,12
3,sample_1,bin_7,bin_2,co-consumed,4.864982,1.362564,87.432810,1.454175,29
4,sample_1,bin_7,bin_2,provided,6.002731,0.297473,8.579646,1.288408,10

In [22]:
from micom.interaction import interactions, summarize_interactions
full = interactions(results, taxa=None, threads=8)
full.shape

full_summary = summarize_interactions(full)
full_summary.shape

Output()

(168, 9)

In [23]:
full_summary

,sample_id,focal,partner,class,flux,mass_flux,C_flux,N_flux,n_ints
0,sample_1,bin_1,bin_2,co-consumed,18.804334,1.857076,56.453670,7.961352,36
1,sample_1,bin_1,bin_2,provided,2.354991,0.326258,14.460314,0.119348,10
2,sample_1,bin_1,bin_2,received,0.908516,0.157815,10.100177,0.086414,4
3,sample_1,bin_1,bin_3,co-consumed,4.809585,0.379668,15.521913,2.259347,33
4,sample_1,bin_1,bin_3,provided,11.802236,1.415454,47.137034,5.440692,13
...,...,...,...,...,...,...,...,...,...
163,sample_1,bin_8,bin_6,provided,7.523174,0.947967,32.138254,7.997216,12
164,sample_1,bin_8,bin_6,received,11.802669,0.880384,29.173876,6.917745,12
165,sample_1,bin_8,bin_7,co-consumed,6.323878,0.405353,13.168440,1.633052,22
166,sample_1,bin_8,bin_7,provided,3.362381,0.334655,14.934031,0.141187,12
167,sample_1,bin_8,bin_7,received,4.708836,0.336086,15.883415,0.781014,9

In [25]:


from micom import Community, data
from micom.elasticity import elasticities

tax = pd.DataFrame({
    'id': ['bin.1', 'bin.2', 'bin.3', 'bin.4','bin.5', 'bin.6', 'bin.7', 'bin.8'],
    'sample_id': ['sample_1', 'sample_1', 'sample_1', 'sample_1','sample_1', 'sample_1', 'sample_1', 'sample_1'],
    'abundance': [0.125, 0.125,0.125,0.125,0.125,0.125,0.125,0.125],
    'phylum': ['Proteobacteria', 'Proteobacteria', 'Proteobacteria', 'Bacteroidota', 'Bacteroidota', 'Bacteroidota', 'Cyanobacteria', 'Proteobacteria'],
    'file': [
    'adjusted_models/bin.1.xml', 
    'adjusted_models/bin.2.xml', 
    'adjusted_models/bin.3.xml', 
    'adjusted_models/bin.4.xml', 
    'adjusted_models/bin.5.xml', 
    'adjusted_models/bin.6.xml', 
    'adjusted_models/bin.7.xml', 
    'adjusted_models/bin.8.xml'
]})
com = Community(tax)

eps = elasticities(com, fraction=1.0, reactions=com.exchanges)
eps.head()

2025-10-02 16:51:49,840 - INFO - building new micom model None.
2025-10-02 16:51:49,842 - INFO - using the cplex solver.
2025-10-02 16:51:49,844 - INFO - 0 individuals with abundances below threshold

Output()

2025-10-02 16:51:49,856 - INFO - reading model from adjusted_models/bin.1.xml
2025-10-02 16:51:53,024 - INFO - converting IDs for bin_1
2025-10-02 16:51:53,034 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2025-10-02 16:51:53,036 - INFO - Identified e0 as the external compartment for bin_1. If that is wrong you may be in trouble...
2025-10-02 16:51:55,205 - INFO - adding reactions for bin_1 to community
2025-10-02 16:51:55,951 - INFO - adding metabolite cpd00009_m to external medium
2025-10-02 16:51:55,955 - INFO - adding metabolite cpd00023_m to external medium
2025-10-02 16:51:55,957 - INFO - adding metabolite cpd00027_m to external medium
2025-10-02 16:51:55,959 - INFO - adding metabolite cpd00028_m to external medium
2025-10-02 16:51:55,962 - INFO - adding metabolite cpd00034_m to external medium
2025-10-02 16:51:55,965 - INFO - adding metabolite cpd00039_m to external medium
2025-10-02 16:51:55,967 - INFO - adding metabolite cpd00041_m to external medium
2025-10-02 16:51:55,970 - INFO - adding metabolite cpd00048_m to external medium
2025-10-02 16:51:55,972 - INFO - adding metabolite cpd00051_m to external medium
2025-10-02 16:51:55,975 - INFO - adding metabolite cpd00053_m to external medium
2025-10-02 16:51:55,977 - INFO - adding metabolite cpd00064_m to external medium
2025-10-02 16:51:55,979 - INFO - adding metabolite cpd00118_m to external medium
2025-10-02 16:51:55,982 - INFO - adding metabolite cpd00119_m to external medium
2025-10-02 16:51:55,984 - INFO - adding metabolite cpd00129_m to external medium
2025-10-02 16:51:55,985 - INFO - adding metabolite cpd00149_m to external medium
2025-10-02 16:51:55,987 - INFO - adding metabolite cpd00156_m to external medium
2025-10-02 16:51:55,989 - INFO - adding metabolite cpd00161_m to external medium
2025-10-02 16:51:55,990 - INFO - adding metabolite cpd00179_m to external medium
2025-10-02 16:51:55,997 - INFO - adding metabolite cpd00244_m to external medium
2025-10-02 16:51:55,999 - INFO - adding metabolite cpd00264_m to external medium
2025-10-02 16:51:56,002 - INFO - adding metabolite cpd00268_m to external medium
2025-10-02 16:51:56,005 - INFO - adding metabolite cpd00266_m to external medium
2025-10-02 16:51:56,008 - INFO - adding metabolite cpd00540_m to external medium
2025-10-02 16:51:56,011 - INFO - adding metabolite cpd08305_m to external medium
2025-10-02 16:51:56,013 - INFO - adding metabolite cpd10516_m to external medium
2025-10-02 16:51:56,016 - INFO - adding metabolite cpd00130_m to external medium
2025-10-02 16:51:56,018 - INFO - adding metabolite cpd00971_m to external medium
2025-10-02 16:51:56,020 - INFO - adding metabolite cpd00067_m to external medium
2025-10-02 16:51:56,023 - INFO - adding metabolite cpd00137_m to external medium
2025-10-02 16:51:56,026 - INFO - adding metabolite cpd00084_m to external medium
2025-10-02 16:51:56,028 - INFO - adding metabolite cpd00013_m to external medium
2025-10-02 16:51:56,029 - INFO - adding metabolite cpd00020_m to external medium
2025-10-02 16:51:56,031 - INFO - adding metabolite cpd00139_m to external medium
2025-10-02 16:51:56,033 - INFO - adding metabolite cpd00029_m to external medium
2025-10-02 16:51:56,034 - INFO - adding metabolite cpd00024_m to external medium
2025-10-02 16:51:56,037 - INFO - adding metabolite cpd00224_m to external medium
2025-10-02 16:51:56,039 - INFO - adding metabolite cpd00063_m to external medium
2025-10-02 16:51:56,042 - INFO - adding metabolite cpd11595_m to external medium
2025-10-02 16:51:56,044 - INFO - adding metabolite cpd10515_m to external medium
2025-10-02 16:51:56,047 - INFO - adding metabolite cpd00047_m to external medium
2025-10-02 16:51:56,049 - INFO - adding metabolite cpd00106_m to external medium
2025-10-02 16:51:56,051 - INFO - adding metabolite cpd00108_m to external medium
2025-10-02 16:51:56,053 - INFO - adding metabolite cpd00164_m to external medium
2025-10-02 16:51:56,056 - INFO - adding metabolite cpd00100_m to external medium
2025-10-02 16:51:56,058 - INFO - adding metabolite cpd00033_m to external medium
2025-10-02 16:51:56,060 - INFO - adding metabolite cpd00205_m to external medium
2025-10-02 16:51:56,062 - INFO - adding metabolite cpd00159_m to external medium
2025-10-02 16:51:56,064 - INFO - adding metabolite cpd01262_m to external medium
2025-10-02 16:51:56,065 - INFO - adding metabolite cpd11574_m to external medium
2025-10-02 16:51:56,068 - INFO - adding metabolite cpd00075_m to external medium
2025-10-02 16:51:56,070 - INFO - adding metabolite cpd00209_m to external medium
2025-10-02 16:51:56,072 - INFO - adding metabolite cpd00396_m to external medium
2025-10-02 16:51:56,075 - INFO - adding metabolite cpd01030_m to external medium
2025-10-02 16:51:56,077 - INFO - adding metabolite cpd00036_m to external medium
2025-10-02 16:51:56,079 - INFO - adding metabolite cpd00280_m to external medium
2025-10-02 16:51:56,080 - INFO - adding metabolite cpd00035_m to external medium
2025-10-02 16:51:56,083 - INFO - adding metabolite cpd00132_m to external medium
2025-10-02 16:51:56,084 - INFO - adding metabolite cpd01012_m to external medium
2025-10-02 16:51:56,086 - INFO - adding metabolite cpd00099_m to external medium
2025-10-02 16:51:56,088 - INFO - adding metabolite cpd00058_m to external medium
2025-10-02 16:51:56,090 - INFO - adding metabolite cpd00221_m to external medium
2025-10-02 16:51:56,093 - INFO - adding metabolite cpd01107_m to external medium
2025-10-02 16:51:56,095 - INFO - adding metabolite cpd01741_m to external medium
2025-10-02 16:51:56,102 - INFO - adding metabolite cpd03847_m to external medium
2025-10-02 16:51:56,105 - INFO - adding metabolite cpd15298_m to external medium
2025-10-02 16:51:56,108 - INFO - adding metabolite cpd00214_m to external medium
2025-10-02 16:51:56,111 - INFO - adding metabolite cpd15237_m to external medium
2025-10-02 16:51:56,114 - INFO - adding metabolite cpd01080_m to external medium
2025-10-02 16:51:56,116 - INFO - adding metabolite cpd15269_m to external medium
2025-10-02 16:51:56,118 - INFO - adding metabolite cpd01113_m to external medium
2025-10-02 16:51:56,121 - INFO - adding metabolite cpd03846_m to external medium
2025-10-02 16:51:56,123 - INFO - adding metabolite cpd00254_m to external medium
2025-10-02 16:51:56,125 - INFO - adding metabolite cpd00305_m to external medium
2025-10-02 16:51:56,128 - INFO - adding metabolite cpd00082_m to external medium
2025-10-02 16:51:56,130 - INFO - adding metabolite cpd00010_m to external medium
2025-10-02 16:51:56,133 - INFO - adding metabolite cpd00054_m to external medium
2025-10-02 16:51:56,135 - INFO - adding metabolite cpd00133_m to external medium
2025-10-02 16:51:56,138 - INFO - adding metabolite cpd00153_m to external medium
2025-10-02 16:51:56,140 - INFO - adding metabolite cpd00210_m to external medium
2025-10-02 16:51:56,141 - INFO - adding metabolite cpd00380_m to external medium
2025-10-02 16:51:56,143 - INFO - adding metabolite cpd00185_m to external medium
2025-10-02 16:51:56,145 - INFO - adding metabolite cpd00152_m to external medium
2025-10-02 16:51:56,147 - INFO - adding metabolite cpd00006_m to external medium
2025-10-02 16:51:56,148 - INFO - adding metabolite cpd00138_m to external medium
2025-10-02 16:51:56,150 - INFO - adding metabolite cpd00180_m to external medium
2025-10-02 16:51:56,154 - INFO - adding metabolite cpd00038_m to external medium
2025-10-02 16:51:56,156 - INFO - adding metabolite cpd02733_m to external medium
2025-10-02 16:51:56,160 - INFO - adding metabolite cpd00001_m to external medium
2025-10-02 16:51:56,162 - INFO - adding metabolite cpd00011_m to external medium
2025-10-02 16:51:56,164 - INFO - adding metabolite cpd00007_m to external medium
2025-10-02 16:51:56,166 - INFO - adding metabolite cpd01981_m to external medium
2025-10-02 16:51:56,168 - INFO - adding metabolite cpd00141_m to external medium
2025-10-02 16:51:56,170 - INFO - adding metabolite cpd00073_m to external medium
2025-10-02 16:51:56,171 - INFO - adding metabolite cpd01861_m to external medium
2025-10-02 16:51:56,173 - INFO - adding metabolite cpd00453_m to external medium
2025-10-02 16:51:56,175 - INFO - adding metabolite cpd00071_m to external medium
2025-10-02 16:51:56,178 - INFO - adding metabolite cpd00150_m to external medium
2025-10-02 16:51:56,180 - INFO - adding metabolite cpd08021_m to external medium
2025-10-02 16:51:56,183 - INFO - adding metabolite cpd00450_m to external medium
2025-10-02 16:51:56,186 - INFO - adding metabolite cpd00363_m to external medium
2025-10-02 16:51:56,188 - INFO - adding metabolite cpd00055_m to external medium
2025-10-02 16:51:56,190 - INFO - adding metabolite cpd00448_m to external medium
2025-10-02 16:51:56,193 - INFO - adding metabolite cpd00025_m to external medium
2025-10-02 16:51:56,195 - INFO - adding metabolite cpd00239_m to external medium
2025-10-02 16:51:56,198 - INFO - adding metabolite cpd11640_m to external medium
2025-10-02 16:51:56,199 - INFO - adding metabolite cpd00359_m to external medium
2025-10-02 16:51:56,202 - INFO - adding metabolite cpd00659_m to external medium
2025-10-02 16:51:56,207 - INFO - adding metabolite cpd00418_m to external medium
2025-10-02 16:51:56,210 - INFO - adding metabolite cpd00371_m to external medium
2025-10-02 16:51:56,212 - INFO - adding metabolite cpd00811_m to external medium
2025-10-02 16:51:56,214 - INFO - adding metabolite cpd00324_m to external medium
2025-10-02 16:51:56,217 - INFO - adding metabolite cpd01024_m to external medium
2025-10-02 16:51:56,219 - INFO - adding metabolite cpd00204_m to external medium
2025-10-02 16:51:56,221 - INFO - adding metabolite cpd00116_m to external medium
2025-10-02 16:51:56,223 - INFO - adding metabolite cpd00528_m to external medium
2025-10-02 16:51:56,225 - INFO - adding metabolite cpd11632_m to external medium
2025-10-02 16:51:56,227 - INFO - adding metabolite cpd03662_m to external medium
2025-10-02 16:51:56,230 - INFO - adding metabolite cpd00178_m to external medium
2025-10-02 16:51:56,232 - INFO - adding metabolite cpd01618_m to external medium
2025-10-02 16:51:56,234 - INFO - adding metabolite cpd00030_m to external medium
2025-10-02 16:51:56,238 - INFO - adding metabolite cpd11451_m to external medium
2025-10-02 16:51:56,240 - INFO - adding metabolite cpd11606_m to external medium
2025-10-02 16:51:56,242 - INFO - adding metabolite cpd00121_m to external medium
2025-10-02 16:51:56,244 - INFO - adding metabolite cpd00314_m to external medium
2025-10-02 16:51:56,245 - INFO - adding metabolite cpd00588_m to external medium
2025-10-02 16:51:56,247 - INFO - adding metabolite cpd00322_m to external medium
2025-10-02 16:51:56,249 - INFO - adding metabolite cpd00107_m to external medium
2025-10-02 16:51:56,252 - INFO - adding metabolite cpd00060_m to external medium
2025-10-02 16:51:56,254 - INFO - adding metabolite cpd00066_m to external medium
2025-10-02 16:51:56,257 - INFO - adding metabolite cpd00065_m to external medium
2025-10-02 16:51:56,259 - INFO - adding metabolite cpd00069_m to external medium
2025-10-02 16:51:56,262 - INFO - adding metabolite cpd00249_m to external medium
2025-10-02 16:51:56,264 - INFO - adding metabolite cpd00276_m to external medium
2025-10-02 16:51:56,266 - INFO - adding metabolite cpd00366_m to external medium
2025-10-02 16:51:56,269 - INFO - adding metabolite cpd00222_m to external medium
2025-10-02 16:51:56,271 - INFO - adding metabolite cpd00105_m to external medium
2025-10-02 16:51:56,274 - INFO - adding metabolite cpd00154_m to external medium
2025-10-02 16:51:56,276 - INFO - adding metabolite cpd00003_m to external medium
2025-10-02 16:51:56,278 - INFO - adding metabolite cpd00017_m to external medium
2025-10-02 16:51:56,281 - INFO - adding metabolite cpd00098_m to external medium
2025-10-02 16:51:56,283 - INFO - adding metabolite cpd00117_m to external medium
2025-10-02 16:51:56,286 - INFO - adding metabolite cpd00220_m to external medium
2025-10-02 16:51:56,288 - INFO - adding metabolite cpd00277_m to external medium
2025-10-02 16:51:56,290 - INFO - adding metabolite cpd00281_m to external medium
2025-10-02 16:51:56,293 - INFO - adding metabolite cpd00367_m to external medium
2025-10-02 16:51:56,295 - INFO - adding metabolite cpd00550_m to external medium
2025-10-02 16:51:56,298 - INFO - adding metabolite cpd00644_m to external medium
2025-10-02 16:51:56,301 - INFO - adding metabolite cpd00653_m to external medium
2025-10-02 16:51:56,304 - INFO - reading model from adjusted_models/bin.2.xml
2025-10-02 16:52:00,273 - INFO - converting IDs for bin_2
2025-10-02 16:52:00,281 - INFO - Compartment `e0` sounds like an external compartment. Using this one without counting boundary reactions.
2025-10-02 16:52:00,283 - INFO - Identified e0 as the external compartment for bin_2. If that is wrong you may be in trouble...
2025-10-02 16:52:02,481 - INFO - adding reactions for bin_2 to community
2025-10-02 16:52:03,390 - INFO - updating import rate for external metabolite cpd00009_m
2025-10-02 16:52:03,393 - INFO - updating import rate for external metabolite cpd00023_m
2025-10-02 16:52:03,395 - INFO - updating import rate for external metabolite cpd00027_m
2025-10-02 16:52:03,397 - INFO - updating import rate for external metabolite cpd00028_m
2025-10-02 16:52:03,399 - INFO - updating import rate for external metabolite cpd00030_m
2025-10-02 16:52:03,401 - INFO - updating import rate for external metabolite cpd00039_m
2025-10-02 16:52:03,403 - INFO - updating import rate for external metabolite cpd00041_m
2025-10-02 16:52:03,405 - INFO - updating import rate for external metabolite cpd00048_m
2025-10-02 16:52:03,407 - INFO - updating import rate for external metabolite cpd00051_m
2025-10-02 16:52:03,409 - INFO - updating import rate for external metabolite cpd00053_m
2025-10-02 16:52:03,411 - INFO - updating import rate for external metabolite cpd00064_m
2025-10-02 16:52:03,413 - INFO - updating import rate for external metabolite cpd00073_m
2025-10-02 16:52:03,415 - INFO - updating import rate for external metabolite cpd00107_m
2025-10-02 16:52:03,417 - INFO - updating import rate for external metabolite cpd00108_m
2025-10-02 16:52:03,419 - INFO - updating import rate for external metabolite cpd00118_m
2025-10-02 16:52:03,421 - INFO - updating import rate for external metabolite cpd00119_m
2025-10-02 16:52:03,423 - INFO - updating import rate for external metabolite cpd00129_m
2025-10-02 16:52:03,425 - INFO - updating import rate for external metabolite cpd00149_m
2025-10-02 16:52:03,427 - INFO - updating import rate for external metabolite cpd00154_m
2025-10-02 16:52:03,429 - INFO - updating import rate for external metabolite cpd00156_m
2025-10-02 16:52:03,431 - INFO - updating import rate for external metabolite cpd00161_m
2025-10-02 16:52:03,433 - INFO - updating import rate for external metabolite cpd00179_m
2025-10-02 16:52:03,435 - INFO - updating import rate for external metabolite cpd00209_m
2025-10-02 16:52:03,437 - INFO - updating import rate for external metabolite cpd00210_m
2025-10-02 16:52:03,439 - INFO - updating import rate for external metabolite cpd00224_m
2025-10-02 16:52:03,441 - INFO - updating import rate for external metabolite cpd00244_m
2025-10-02 16:52:03,443 - INFO - updating import rate for external metabolite cpd00264_m
2025-10-02 16:52:03,445 - INFO - updating import rate for external metabolite cpd00268_m
2025-10-02 16:52:03,447 - INFO - updating import rate for external metabolite cpd00322_m
2025-10-02 16:52:03,449 - INFO - adding metabolite cpd03724_m to external medium
2025-10-02 16:52:03,452 - INFO - updating import rate for external metabolite cpd10516_m
2025-10-02 16:52:03,454 - INFO - updating import rate for external metabolite cpd00067_m
2025-10-02 16:52:03,456 - INFO - updating import rate for external metabolite cpd00249_m
2025-10-02 16:52:03,458 - INFO - updating import rate for external metabolite cpd00130_m
2025-10-02 16:52:03,460 - INFO - updating import rate for external metabolite cpd00971_m
2025-10-02 16:52:03,462 - INFO - updating import rate for external metabolite cpd00137_m
2025-10-02 16:52:03,464 - INFO - updating import rate for external metabolite cpd00035_m
2025-10-02 16:52:03,466 - INFO - updating import rate for external metabolite cpd00060_m
2025-10-02 16:52:03,468 - INFO - updating import rate for external metabolite cpd00084_m
2025-10-02 16:52:03,470 - INFO - updating import rate for external metabolite cpd00013_m
2025-10-02 16:52:03,472 - INFO - updating import rate for external metabolite cpd00020_m
2025-10-02 16:52:03,475 - INFO - updating import rate for external metabolite cpd00139_m
2025-10-02 16:52:03,484 - INFO - updating import rate for external metabolite cpd00029_m
2025-10-02 16:52:03,487 - INFO - updating import rate for external metabolite cpd00132_m
2025-10-02 16:52:03,490 - INFO - updating import rate for external metabolite cpd11595_m
2025-10-02 16:52:03,492 - INFO - updating import rate for external metabolite cpd10515_m
2025-10-02 16:52:03,494 - INFO - updating import rate for external metabolite cpd00082_m
2025-10-02 16:52:03,496 - INFO - updating import rate for external metabolite cpd00106_m
2025-10-02 16:52:03,498 - INFO - updating import rate for external metabolite cpd00033_m
2025-10-02 16:52:03,500 - INFO - updating import rate for external metabolite cpd00205_m
2025-10-02 16:52:03,502 - INFO - adding metabolite cpd00208_m to external medium
2025-10-02 16:52:03,505 - INFO - updating import rate for external metabolite cpd00159_m
2025-10-02 16:52:03,507 - INFO - updating import rate for external metabolite cpd01262_m
2025-10-02 16:52:03,509 - INFO - updating import rate for external metabolite cpd11574_m
2025-10-02 16:52:03,511 - INFO - adding metabolite cpd01132_m to external medium
2025-10-02 16:52:03,513 - INFO - updating import rate for external metabolite cpd00396_m
2025-10-02 16:52:03,515 - INFO - updating import rate for external metabolite cpd00036_m
2025-10-02 16:52:03,517 - INFO - adding metabolite cpd01217_m to external medium
2025-10-02 16:52:03,520 - INFO - adding metabolite cpd00751_m to external medium
2025-10-02 16:52:03,522 - INFO - updating import rate for external metabolite cpd01012_m
2025-10-02 16:52:03,524 - INFO - updating import rate for external metabolite cpd00099_m
2025-10-02 16:52:03,526 - INFO - updating import rate for external metabolite cpd00058_m
2025-10-02 16:52:03,528 - INFO - adding metabolite cpd01015_m to external medium
2025-10-02 16:52:03,531 - INFO - updating import rate for external metabolite cpd00277_m
2025-10-02 16:52:03,533 - INFO - updating import rate for external metabolite cpd00221_m
2025-10-02 16:52:03,535 - INFO - adding metabolite cpd00412_m to external medium
2025-10-02 16:52:03,537 - INFO - updating import rate for external metabolite cpd01107_m
2025-10-02 16:52:03,540 - INFO - updating import rate for external metabolite cpd01741_m
2025-10-02 16:52:03,542 - INFO - updating import rate for external metabolite cpd03847_m
2025-10-02 16:52:03,544 - INFO - updating import rate for external metabolite cpd15298_m
2025-10-02 16:52:03,546 - INFO - updating import rate for external metabolite cpd00214_m
2025-10-02 16:52:03,547 - INFO - updating import rate for external metabolite cpd15237_m
2025-10-02 16:52:03,550 - INFO - updating import rate for external metabolite cpd01080_m
2025-10-02 16:52:03,551 - INFO - updating import rate for external metabolite cpd15269_m
2025-10-02 16:52:03,553 - INFO - updating import rate for external metabolite cpd01113_m
2025-10-02 16:52:03,555 - INFO - updating import rate for external metabolite cpd03846_m
2025-10-02 16:52:03,557 - INFO - adding metabolite cpd03587_m to external medium
2025-10-02 16:52:03,560 - INFO - updating import rate for external metabolite cpd00254_m
2025-10-02 16:52:03,561 - INFO - updating import rate for external metabolite cpd00034_m
2025-10-02 16:52:03,563 - INFO - updating import rate for external metabolite cpd00305_m

2025-10-02 16:52:42,586 - INFO - adding L2 norm to None
2025-10-02 16:52:42,594 - INFO - finished adding tradeoff objective to None
2025-10-02 16:52:43,376 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:52:43,439 - INFO - Starting crossover...
2025-10-02 16:52:43,441 - INFO - constraining growth rates.
2025-10-02 16:52:43,450 - INFO - finding closest feasible solution

Output()

2025-10-02 16:52:44,907 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:52:44,977 - INFO - Starting crossover...
2025-10-02 16:52:44,978 - INFO - constraining growth rates.
2025-10-02 16:52:44,989 - INFO - finding closest feasible solution
2025-10-02 16:52:46,352 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:52:46,419 - INFO - Starting crossover...
2025-10-02 16:52:46,421 - INFO - constraining growth rates.
2025-10-02 16:52:46,430 - INFO - finding closest feasible solution
2025-10-02 16:52:47,802 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:52:47,863 - INFO - Starting crossover...
2025-10-02 16:52:47,864 - INFO - constraining growth rates.
2025-10-02 16:52:47,874 - INFO - finding closest feasible solution
2025-10-02 16:52:49,227 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:52:49,296 - INFO - Starting crossover...
2025-10-02 16:52:49,297 - INFO - constraining growth rates.
2025-10-02 16:52:49,309 - INFO - finding closest feasible solution
2025-10-02 16:52:50,730 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:52:50,793 - INFO - Starting crossover...
2025-10-02 16:52:50,798 - INFO - constraining growth rates.
2025-10-02 16:52:50,811 - INFO - finding closest feasible solution
2025-10-02 16:52:52,201 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:52:52,260 - INFO - Starting crossover...
2025-10-02 16:52:52,262 - INFO - constraining growth rates.
2025-10-02 16:52:52,271 - INFO - finding closest feasible solution
2025-10-02 16:52:53,604 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:52:53,665 - INFO - Starting crossover...
2025-10-02 16:52:53,667 - INFO - constraining growth rates.
2025-10-02 16:52:53,677 - INFO - finding closest feasible solution
2025-10-02 16:52:55,047 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:52:55,116 - INFO - Starting crossover...
2025-10-02 16:52:55,117 - INFO - constraining growth rates.
2025-10-02 16:52:55,127 - INFO - finding closest feasible solution
2025-10-02 16:52:56,495 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:52:56,556 - INFO - Starting crossover...
2025-10-02 16:52:56,557 - INFO - constraining growth rates.
2025-10-02 16:52:56,569 - INFO - finding closest feasible solution
2025-10-02 16:52:57,929 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:52:57,997 - INFO - Starting crossover...
2025-10-02 16:52:57,999 - INFO - constraining growth rates.
2025-10-02 16:52:58,010 - INFO - finding closest feasible solution
2025-10-02 16:52:59,372 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:52:59,430 - INFO - Starting crossover...
2025-10-02 16:52:59,432 - INFO - constraining growth rates.
2025-10-02 16:52:59,442 - INFO - finding closest feasible solution
2025-10-02 16:53:00,812 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:53:00,880 - INFO - Starting crossover...
2025-10-02 16:53:00,882 - INFO - constraining growth rates.
2025-10-02 16:53:00,891 - INFO - finding closest feasible solution
2025-10-02 16:53:02,232 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:53:02,293 - INFO - Starting crossover...
2025-10-02 16:53:02,300 - INFO - constraining growth rates.
2025-10-02 16:53:02,314 - INFO - finding closest feasible solution
2025-10-02 16:53:03,669 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:53:03,736 - INFO - Starting crossover...
2025-10-02 16:53:03,738 - INFO - constraining growth rates.
2025-10-02 16:53:03,748 - INFO - finding closest feasible solution
2025-10-02 16:53:05,103 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:53:05,174 - INFO - Starting crossover...
2025-10-02 16:53:05,176 - INFO - constraining growth rates.
2025-10-02 16:53:05,189 - INFO - finding closest feasible solution

2025-10-02 16:53:05,771 - INFO - adding L2 norm to None
2025-10-02 16:53:05,785 - INFO - finished adding tradeoff objective to None
2025-10-02 16:53:06,565 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:53:06,626 - INFO - Starting crossover...
2025-10-02 16:53:06,627 - INFO - constraining growth rates.
2025-10-02 16:53:06,636 - INFO - finding closest feasible solution

Output()

2025-10-02 16:53:07,170 - INFO - setting new abundances for None
2025-10-02 16:53:07,172 - INFO - updating exchange reactions for None
2025-10-02 16:53:07,355 - INFO - updating the community objective for None
2025-10-02 16:53:08,218 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:53:08,284 - INFO - Starting crossover...
2025-10-02 16:53:08,285 - INFO - constraining growth rates.
2025-10-02 16:53:08,296 - INFO - finding closest feasible solution
2025-10-02 16:53:08,857 - INFO - setting new abundances for None
2025-10-02 16:53:08,859 - INFO - updating exchange reactions for None
2025-10-02 16:53:09,051 - INFO - updating the community objective for None
2025-10-02 16:53:09,062 - INFO - setting new abundances for None
2025-10-02 16:53:09,064 - INFO - updating exchange reactions for None
2025-10-02 16:53:09,263 - INFO - updating the community objective for None
2025-10-02 16:53:10,081 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:53:10,140 - INFO - Starting crossover...
2025-10-02 16:53:10,141 - INFO - constraining growth rates.
2025-10-02 16:53:10,154 - INFO - finding closest feasible solution
2025-10-02 16:53:10,693 - INFO - setting new abundances for None
2025-10-02 16:53:10,695 - INFO - updating exchange reactions for None
2025-10-02 16:53:10,891 - INFO - updating the community objective for None
2025-10-02 16:53:10,902 - INFO - setting new abundances for None
2025-10-02 16:53:10,903 - INFO - updating exchange reactions for None
2025-10-02 16:53:11,100 - INFO - updating the community objective for None
2025-10-02 16:53:11,880 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:53:11,949 - INFO - Starting crossover...
2025-10-02 16:53:11,950 - INFO - constraining growth rates.
2025-10-02 16:53:11,962 - INFO - finding closest feasible solution
2025-10-02 16:53:12,512 - INFO - setting new abundances for None
2025-10-02 16:53:12,514 - INFO - updating exchange reactions for None
2025-10-02 16:53:12,716 - INFO - updating the community objective for None
2025-10-02 16:53:12,727 - INFO - setting new abundances for None
2025-10-02 16:53:12,729 - INFO - updating exchange reactions for None
2025-10-02 16:53:12,924 - INFO - updating the community objective for None
2025-10-02 16:53:13,719 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:53:13,779 - INFO - Starting crossover...
2025-10-02 16:53:13,783 - INFO - constraining growth rates.
2025-10-02 16:53:13,796 - INFO - finding closest feasible solution
2025-10-02 16:53:14,333 - INFO - setting new abundances for None
2025-10-02 16:53:14,338 - INFO - updating exchange reactions for None
2025-10-02 16:53:15,432 - INFO - updating the community objective for None
2025-10-02 16:53:15,443 - INFO - setting new abundances for None
2025-10-02 16:53:15,444 - INFO - updating exchange reactions for None
2025-10-02 16:53:15,634 - INFO - updating the community objective for None
2025-10-02 16:53:16,468 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:53:16,542 - INFO - Starting crossover...
2025-10-02 16:53:16,543 - INFO - constraining growth rates.
2025-10-02 16:53:16,556 - INFO - finding closest feasible solution
2025-10-02 16:53:17,135 - INFO - setting new abundances for None
2025-10-02 16:53:17,136 - INFO - updating exchange reactions for None
2025-10-02 16:53:17,330 - INFO - updating the community objective for None
2025-10-02 16:53:17,341 - INFO - setting new abundances for None
2025-10-02 16:53:17,342 - INFO - updating exchange reactions for None
2025-10-02 16:53:17,529 - INFO - updating the community objective for None
2025-10-02 16:53:18,337 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:53:18,400 - INFO - Starting crossover...
2025-10-02 16:53:18,402 - INFO - constraining growth rates.
2025-10-02 16:53:18,413 - INFO - finding closest feasible solution
2025-10-02 16:53:18,977 - INFO - setting new abundances for None
2025-10-02 16:53:18,979 - INFO - updating exchange reactions for None
2025-10-02 16:53:19,167 - INFO - updating the community objective for None
2025-10-02 16:53:19,183 - INFO - setting new abundances for None
2025-10-02 16:53:19,186 - INFO - updating exchange reactions for None
2025-10-02 16:53:19,370 - INFO - updating the community objective for None
2025-10-02 16:53:20,234 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:53:20,296 - INFO - Starting crossover...
2025-10-02 16:53:20,297 - INFO - constraining growth rates.
2025-10-02 16:53:20,308 - INFO - finding closest feasible solution
2025-10-02 16:53:20,863 - INFO - setting new abundances for None
2025-10-02 16:53:20,865 - INFO - updating exchange reactions for None
2025-10-02 16:53:21,046 - INFO - updating the community objective for None
2025-10-02 16:53:21,057 - INFO - setting new abundances for None
2025-10-02 16:53:21,058 - INFO - updating exchange reactions for None
2025-10-02 16:53:21,246 - INFO - updating the community objective for None
2025-10-02 16:53:22,052 - INFO - solver returned the status numeric, returning the solution anyway.
2025-10-02 16:53:22,115 - INFO - Starting crossover...
2025-10-02 16:53:22,121 - INFO - constraining growth rates.
2025-10-02 16:53:22,136 - INFO - finding closest feasible solution
2025-10-02 16:53:22,700 - INFO - setting new abundances for None
2025-10-02 16:53:22,702 - INFO - updating exchange reactions for None
2025-10-02 16:53:22,893 - INFO - updating the community objective for None

        reaction   taxon       effector direction  elasticity       type
0  EX_cpd00009_m  medium  EX_cpd00009_m   reverse         0.0  exchanges
1  EX_cpd00023_m  medium  EX_cpd00009_m      zero         0.0  exchanges
2  EX_cpd00027_m  medium  EX_cpd00009_m      zero         0.0  exchanges
3  EX_cpd00028_m  medium  EX_cpd00009_m      zero         0.0  exchanges
4  EX_cpd00034_m  medium  EX_cpd00009_m   reverse         0.0  exchanges

In [36]:
# Filter rows where elasticity is not zero and effector is EX_cpd11606_m
filtered_eps = eps[(eps['elasticity'] != 0)]

with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(filtered_eps)

           reaction   taxon       effector direction    elasticity       type
828   EX_cpd00009_m  medium  EX_cpd10516_m   reverse  3.122747e-01  exchanges
829   EX_cpd00023_m  medium  EX_cpd10516_m      zero  1.558075e-05  exchanges
830   EX_cpd00027_m  medium  EX_cpd10516_m      zero  1.917307e-06  exchanges
831   EX_cpd00028_m  medium  EX_cpd10516_m      zero  6.993304e-06  exchanges
832   EX_cpd00034_m  medium  EX_cpd10516_m   reverse -2.220066e-03  exchanges
833   EX_cpd00039_m  medium  EX_cpd10516_m      zero  1.115655e-05  exchanges
834   EX_cpd00041_m  medium  EX_cpd10516_m      zero  2.289181e-05  exchanges
835   EX_cpd00048_m  medium  EX_cpd10516_m   reverse -3.523353e-03  exchanges
836   EX_cpd00051_m  medium  EX_cpd10516_m      zero  1.202138e-05  exchanges
837   EX_cpd00053_m  medium  EX_cpd10516_m      zero  1.558822e-05  exchanges
838   EX_cpd00064_m  medium  EX_cpd10516_m      zero  1.266837e-05  exchanges
839   EX_cpd00118_m  medium  EX_cpd10516_m      zero  1.260665e-05  exchanges
840   EX_cpd00119_m  medium  EX_cpd10516_m      zero  1.161428e-05  exchanges
841   EX_cpd00129_m  medium  EX_cpd10516_m      zero  1.288801e-05  exchanges
842   EX_cpd00149_m  medium  EX_cpd10516_m   reverse -2.223550e-03  exchanges
843   EX_cpd00156_m  medium  EX_cpd10516_m      zero  1.188501e-05  exchanges
844   EX_cpd00161_m  medium  EX_cpd10516_m      zero  1.706091e-05  exchanges
845   EX_cpd00179_m  medium  EX_cpd10516_m      zero  1.752920e-06  exchanges
846   EX_cpd00244_m  medium  EX_cpd10516_m      zero  9.158361e-06  exchanges
847   EX_cpd00264_m  medium  EX_cpd10516_m      zero  7.492340e-06  exchanges
850   EX_cpd00540_m  medium  EX_cpd10516_m      zero  4.043223e-06  exchanges
852   EX_cpd10516_m  medium  EX_cpd10516_m   reverse -2.900453e-03  exchanges
853   EX_cpd00130_m  medium  EX_cpd10516_m      zero  2.314669e-05  exchanges
854   EX_cpd00971_m  medium  EX_cpd10516_m      zero  8.400777e-06  exchanges
855   EX_cpd00067_m  medium  EX_cpd10516_m   forward -3.055969e-02  exchanges
856   EX_cpd00137_m  medium  EX_cpd10516_m   reverse  1.732986e-07  exchanges
857   EX_cpd00084_m  medium  EX_cpd10516_m      zero  2.299939e-05  exchanges
858   EX_cpd00013_m  medium  EX_cpd10516_m   reverse  6.494932e-03  exchanges
859   EX_cpd00020_m  medium  EX_cpd10516_m      zero  2.780174e-05  exchanges
860   EX_cpd00139_m  medium  EX_cpd10516_m      zero  4.421008e-05  exchanges
861   EX_cpd00029_m  medium  EX_cpd10516_m      zero  5.479913e-05  exchanges
862   EX_cpd00024_m  medium  EX_cpd10516_m      zero  1.756732e-05  exchanges
863   EX_cpd00224_m  medium  EX_cpd10516_m      zero  1.269807e-05  exchanges
864   EX_cpd00063_m  medium  EX_cpd10516_m   reverse -2.223504e-03  exchanges
866   EX_cpd10515_m  medium  EX_cpd10516_m      zero  5.401668e-04  exchanges
867   EX_cpd00047_m  medium  EX_cpd10516_m      zero  1.461320e-04  exchanges
868   EX_cpd00106_m  medium  EX_cpd10516_m      zero  2.316269e-05  exchanges
869   EX_cpd00108_m  medium  EX_cpd10516_m      zero  1.083586e-05  exchanges
870   EX_cpd00164_m  medium  EX_cpd10516_m      zero  2.265472e-05  exchanges
871   EX_cpd00100_m  medium  EX_cpd10516_m      zero  1.909715e-05  exchanges
872   EX_cpd00033_m  medium  EX_cpd10516_m      zero  4.438236e-05  exchanges
873   EX_cpd00205_m  medium  EX_cpd10516_m   reverse -2.223677e-03  exchanges
874   EX_cpd00159_m  medium  EX_cpd10516_m      zero  2.443710e-05  exchanges
877   EX_cpd00075_m  medium  EX_cpd10516_m   forward  1.248299e-02  exchanges
878   EX_cpd00209_m  medium  EX_cpd10516_m      zero  1.504873e-06  exchanges
881   EX_cpd00036_m  medium  EX_cpd10516_m      zero  2.157004e-05  exchanges
883   EX_cpd00035_m  medium  EX_cpd10516_m      zero  2.335494e-05  exchanges
884   EX_cpd00132_m  medium  EX_cpd10516_m      zero  2.200890e-05  exchanges
885   EX_cpd01012_m  medium  EX_cpd10516_m      zero  9.110841e-06  exchanges
886   EX_cpd00099_m  medium  EX_cpd10516_m   reverse -2.223664e-03  exchanges
887   EX_cpd00058_m  medium  EX_cpd10516_m   reverse -2.223600e-03  exchanges
888   EX_cpd00221_m  medium  EX_cpd10516_m      zero  2.332175e-05  exchanges
890   EX_cpd01741_m  medium  EX_cpd10516_m      zero  1.484333e-05  exchanges
899   EX_cpd00254_m  medium  EX_cpd10516_m   reverse -2.216302e-03  exchanges
900   EX_cpd00305_m  medium  EX_cpd10516_m      zero  2.605410e-05  exchanges
901   EX_cpd00082_m  medium  EX_cpd10516_m      zero  1.088062e-05  exchanges
902   EX_cpd00010_m  medium  EX_cpd10516_m      zero  1.461545e-05  exchanges
903   EX_cpd00054_m  medium  EX_cpd10516_m      zero  2.717578e-05  exchanges
904   EX_cpd00133_m  medium  EX_cpd10516_m      zero  3.001426e-05  exchanges
906   EX_cpd00210_m  medium  EX_cpd10516_m      zero  2.505681e-05  exchanges
907   EX_cpd00380_m  medium  EX_cpd10516_m      zero  1.604882e-05  exchanges
910   EX_cpd00006_m  medium  EX_cpd10516_m      zero  3.362203e-06  exchanges
911   EX_cpd00138_m  medium  EX_cpd10516_m      zero  1.079976e-05  exchanges
912   EX_cpd00180_m  medium  EX_cpd10516_m      zero  1.395528e-04  exchanges
913   EX_cpd00038_m  medium  EX_cpd10516_m      zero  3.078095e-05  exchanges
915   EX_cpd00001_m  medium  EX_cpd10516_m   forward -1.517524e-02  exchanges
916   EX_cpd00011_m  medium  EX_cpd10516_m   forward  4.710535e-03  exchanges
917   EX_cpd00007_m  medium  EX_cpd10516_m   reverse  4.802157e-02  exchanges
919   EX_cpd00141_m  medium  EX_cpd10516_m      zero  2.650356e-05  exchanges
920   EX_cpd00073_m  medium  EX_cpd10516_m      zero  6.660275e-04  exchanges
921   EX_cpd01861_m  medium  EX_cpd10516_m      zero  2.002175e-06  exchanges
922   EX_cpd00453_m  medium  EX_cpd10516_m      zero  2.002164e-06  exchanges
923   EX_cpd00071_m  medium  EX_cpd10516_m      zero  2.774740e-05  exchanges
924   EX_cpd00150_m  medium  EX_cpd10516_m      zero  1.976800e-06  exchanges
927   EX_cpd00363_m  medium  EX_cpd10516_m      zero  2.334090e-05  exchanges
928   EX_cpd00055_m  medium  EX_cpd10516_m      zero  6.943353e-05  exchanges
929   EX_cpd00448_m  medium  EX_cpd10516_m      zero  2.195360e-05  exchanges
930   EX_cpd00025_m  medium  EX_cpd10516_m   forward  2.415833e+00  exchanges
931   EX_cpd00239_m  medium  EX_cpd10516_m      zero  2.266295e-04  exchanges
932   EX_cpd11640_m  medium  EX_cpd10516_m      zero  1.508643e-04  exchanges
933   EX_cpd00359_m  medium  EX_cpd10516_m      zero  7.771071e-06  exchanges
934   EX_cpd00659_m  medium  EX_cpd10516_m      zero  2.473668e-04  exchanges
935   EX_cpd00418_m  medium  EX_cpd10516_m      zero  1.451710e-03  exchanges
936   EX_cpd00371_m  medium  EX_cpd10516_m      zero  2.287556e-05  exchanges
938   EX_cpd00324_m  medium  EX_cpd10516_m      zero  6.805754e-05  exchanges
941   EX_cpd00116_m  medium  EX_cpd10516_m      zero  4.707635e-05  exchanges
943   EX_cpd11632_m  medium  EX_cpd10516_m   reverse -1.147527e-11  exchanges
947   EX_cpd00030_m  medium  EX_cpd10516_m   reverse -2.218283e-03  exchanges
948   EX_cpd11451_m  medium  EX_cpd10516_m      zero  9.193562e-06  exchanges
949   EX_cpd11606_m  medium  EX_cpd10516_m      zero  9.663201e-06  exchanges
950   EX_cpd00121_m  medium  EX_cpd10516_m      zero  8.678769e-05  exchanges
951   EX_cpd00314_m  medium  EX_cpd10516_m      zero  1.004782e-05  exchanges
952   EX_cpd00588_m  medium  EX_cpd10516_m      zero  1.015027e-05  exchanges
953   EX_cpd00322_m  medium  EX_cpd10516_m      zero  9.885395e-06  exchanges
954   EX_cpd00107_m  medium  EX_cpd10516_m      zero  9.540220e-06  exchanges
955   EX_cpd00060_m  medium  EX_cpd10516_m      zero  1.377912e-05  exchanges
956   EX_cpd00066_m  medium  EX_cpd10516_m      zero  7.761883e-06  exchanges
957   EX_cpd00065_m  medium  EX_cpd10516_m      zero  6.031887e-06  exchanges
958   EX_cpd00069_m  medium  EX_cpd10516_m      zero  9.041962e-06  exchanges
959   EX_cpd00249_m  medium  EX_cpd10516_m      zero  8.709213e-06  exchanges
961   EX_cpd00366_m  medium  EX_cpd10516_m      zero  1.170243e-05  exchanges
962   EX_cpd00222_m  medium  EX_cpd10516_m      zero  1.177883e-05  exchanges
963   EX_cpd00105_m  medium  EX_cpd10516_m      zero  1.270198e-05  exchanges
964   EX_cpd00154_m  medium  EX_cpd10516_m      zero  1.269066e-05  exchanges
965   EX_cpd00003_m  medium  EX_cpd10516_m      zero  3.419632e-06  exchanges
966   EX_cpd00017_m  medium  EX_cpd10516_m      zero  4.900738e-06  exchanges
967   EX_cpd00098_m  medium  EX_cpd10516_m      zero  1.431239e-06  exchanges
968   EX_cpd00117_m  medium  EX_cpd10516_m      zero  2.335568e-05  exchanges
969   EX_cpd00220_m  medium  EX_cpd10516_m      zero  4.890854e-06  exchanges
970   EX_cpd00277_m  medium  EX_cpd10516_m      zero  8.086913e-06  exchanges
971   EX_cpd00281_m  medium  EX_cpd10516_m      zero  1.596599e-05  exchanges
972   EX_cpd00367_m  medium  EX_cpd10516_m      zero  8.618929e-06  exchanges
973   EX_cpd00550_m  medium  EX_cpd10516_m      zero  2.717684e-05  exchanges
974   EX_cpd00644_m  medium  EX_cpd10516_m      zero  7.218886e-06  exchanges
977   EX_cpd00208_m  medium  EX_cpd10516_m      zero  1.304348e-06  exchanges
979   EX_cpd01217_m  medium  EX_cpd10516_m      zero  8.575097e-06  exchanges
981   EX_cpd01015_m  medium  EX_cpd10516_m      zero  2.365103e-06  exchanges
982   EX_cpd00412_m  medium  EX_cpd10516_m      zero  8.386033e-06  exchanges
983   EX_cpd03587_m  medium  EX_cpd10516_m      zero  4.615364e-06  exchanges
986   EX_cpd00794_m  medium  EX_cpd10516_m      zero  1.753674e-06  exchanges
997   EX_cpd00246_m  medium  EX_cpd10516_m      zero  8.112794e-06  exchanges
998   EX_cpd00142_m  medium  EX_cpd10516_m      zero  1.745732e-05  exchanges
999   EX_cpd00182_m  medium  EX_cpd10516_m      zero  7.938511e-06  exchanges
1000  EX_cpd00311_m  medium  EX_cpd10516_m      zero  8.262129e-06  exchanges
1002  EX_cpd00092_m  medium  EX_cpd10516_m      zero  4.060115e-05  exchanges
1003  EX_cpd00309_m  medium  EX_cpd10516_m      zero  4.603146e-05  exchanges
1005  EX_cpd00012_m  medium  EX_cpd10516_m   forward  4.454578e-01  exchanges
1009  EX_cpd00136_m  medium  EX_cpd10516_m      zero  1.114986e-05  exchanges
1013  EX_cpd00076_m  medium  EX_cpd10516_m      zero  5.331011e-06  exchanges
1014  EX_cpd00306_m  medium  EX_cpd10516_m      zero  1.169417e-05  exchanges
1015  EX_cpd00158_m  medium  EX_cpd10516_m      zero  1.579653e-06  exchanges
1017  EX_cpd11842_m  medium  EX_cpd10516_m      zero  2.061223e-06  exchanges
1018  EX_cpd00122_m  medium  EX_cpd10516_m      zero  8.253580e-06  exchanges
1019  EX_cpd21520_m  medium  EX_cpd10516_m      zero  6.409830e-06  exchanges
1021  EX_cpd00832_m  medium  EX_cpd10516_m      zero  1.281849e-05  exchanges
1022  EX_cpd90017_m  medium  EX_cpd10516_m      zero  1.281849e-05  exchanges
1031  EX_cpd90022_m  medium  EX_cpd10516_m      zero  1.068184e-06  exchanges
1032  EX_cpd03198_m  medium  EX_cpd10516_m      zero  1.500364e-06  exchanges
1033  EX_cpd00232_m  medium  EX_cpd10516_m      zero  6.280764e-06  exchanges
1034  EX_cpd00184_m  medium  EX_cpd10516_m      zero  7.202544e-06  exchanges
1035  EX_cpd00009_m  medium  EX_cpd00137_m   reverse  8.519630e-01  exchanges
1036  EX_cpd00023_m  medium  EX_cpd00137_m      zero  1.613531e-06  exchanges
1037  EX_cpd00027_m  medium  EX_cpd00137_m      zero  3.776027e-08  exchanges
1038  EX_cpd00028_m  medium  EX_cpd00137_m      zero  1.093544e-06  exchanges
1039  EX_cpd00034_m  medium  EX_cpd00137_m   reverse  8.535367e-01  exchanges
1040  EX_cpd00039_m  medium  EX_cpd00137_m      zero  1.278996e-06  exchanges
1041  EX_cpd00041_m  medium  EX_cpd00137_m      zero  2.371974e-06  exchanges
1042  EX_cpd00048_m  medium  EX_cpd00137_m   reverse  8.537429e-01  exchanges
1043  EX_cpd00051_m  medium  EX_cpd00137_m      zero  1.255022e-06  exchanges
1044  EX_cpd00053_m  medium  EX_cpd00137_m      zero  1.613857e-06  exchanges
1045  EX_cpd00064_m  medium  EX_cpd00137_m      zero  1.314224e-06  exchanges
1046  EX_cpd00118_m  medium  EX_cpd00137_m      zero  1.303294e-06  exchanges
1047  EX_cpd00119_m  medium  EX_cpd00137_m      zero  1.218940e-06  exchanges
1048  EX_cpd00129_m  medium  EX_cpd00137_m      zero  1.331875e-06  exchanges
1049  EX_cpd00149_m  medium  EX_cpd00137_m   reverse  8.535367e-01  exchanges
1050  EX_cpd00156_m  medium  EX_cpd00137_m      zero  1.223881e-06  exchanges
1051  EX_cpd00161_m  medium  EX_cpd00137_m      zero  1.768823e-06  exchanges
1052  EX_cpd00179_m  medium  EX_cpd00137_m      zero  4.874620e-08  exchanges
1053  EX_cpd00244_m  medium  EX_cpd00137_m      zero  6.926548e-08  exchanges
1054  EX_cpd00264_m  medium  EX_cpd00137_m      zero  7.712731e-07  exchanges
1057  EX_cpd00540_m  medium  EX_cpd00137_m      zero  9.347028e-08  exchanges
1059  EX_cpd10516_m  medium  EX_cpd00137_m   reverse  8.536815e-01  exchanges
1060  EX_cpd00130_m  medium  EX_cpd00137_m      zero  2.398034e-06  exchanges
1061  EX_cpd00971_m  medium  EX_cpd00137_m      zero  3.101146e-09  exchanges
1062  EX_cpd00067_m  medium  EX_cpd00137_m   forward  4.957963e-01  exchanges
1063  EX_cpd00137_m  medium  EX_cpd00137_m   reverse  9.999998e-01  exchanges
1064  EX_cpd00084_m  medium  EX_cpd00137_m      zero  2.381184e-06  exchanges
1065  EX_cpd00013_m  medium  EX_cpd00137_m   reverse  8.920391e-01  exchanges
1066  EX_cpd00020_m  medium  EX_cpd00137_m      zero  2.874567e-06  exchanges
1067  EX_cpd00139_m  medium  EX_cpd00137_m      zero  4.568731e-06  exchanges
1068  EX_cpd00029_m  medium  EX_cpd00137_m      zero  4.677765e-06  exchanges
1069  EX_cpd00024_m  medium  EX_cpd00137_m      zero  1.818778e-06  exchanges
1070  EX_cpd00224_m  medium  EX_cpd00137_m      zero  1.294411e-06  exchanges
1071  EX_cpd00063_m  medium  EX_cpd00137_m   reverse  8.535367e-01  exchanges
1073  EX_cpd10515_m  medium  EX_cpd00137_m      zero  8.910741e-05  exchanges
1074  EX_cpd00047_m  medium  EX_cpd00137_m      zero  1.522322e-05  exchanges
1075  EX_cpd00106_m  medium  EX_cpd00137_m      zero  2.398817e-06  exchanges
1076  EX_cpd00108_m  medium  EX_cpd00137_m      zero  1.120168e-06  exchanges
1077  EX_cpd00164_m  medium  EX_cpd00137_m      zero  2.403730e-06  exchanges
1078  EX_cpd00100_m  medium  EX_cpd00137_m      zero  1.966715e-06  exchanges
1079  EX_cpd00033_m  medium  EX_cpd00137_m      zero  4.585754e-06  exchanges
1080  EX_cpd00205_m  medium  EX_cpd00137_m   reverse  8.535367e-01  exchanges
1081  EX_cpd00159_m  medium  EX_cpd00137_m      zero  2.528632e-06  exchanges
1084  EX_cpd00075_m  medium  EX_cpd00137_m   forward  9.194965e-01  exchanges
1085  EX_cpd00209_m  medium  EX_cpd00137_m      zero  6.269705e-09  exchanges
1088  EX_cpd00036_m  medium  EX_cpd00137_m      zero  2.186737e-06  exchanges
1090  EX_cpd00035_m  medium  EX_cpd00137_m      zero  2.418134e-06  exchanges
1091  EX_cpd00132_m  medium  EX_cpd00137_m      zero  2.295781e-06  exchanges
1092  EX_cpd01012_m  medium  EX_cpd00137_m      zero  3.787809e-08  exchanges
1093  EX_cpd00099_m  medium  EX_cpd00137_m   reverse  8.535367e-01  exchanges
1094  EX_cpd00058_m  medium  EX_cpd00137_m   reverse  8.535367e-01  exchanges
1095  EX_cpd00221_m  medium  EX_cpd00137_m      zero  2.416679e-06  exchanges
1097  EX_cpd01741_m  medium  EX_cpd00137_m      zero  5.291535e-06  exchanges
1106  EX_cpd00254_m  medium  EX_cpd00137_m   reverse  8.535367e-01  exchanges
1107  EX_cpd00305_m  medium  EX_cpd00137_m      zero  3.451429e-06  exchanges
1108  EX_cpd00082_m  medium  EX_cpd00137_m      zero  1.121713e-06  exchanges
1109  EX_cpd00010_m  medium  EX_cpd00137_m      zero  2.095140e-06  exchanges
1110  EX_cpd00054_m  medium  EX_cpd00137_m      zero  2.791041e-06  exchanges
1111  EX_cpd00133_m  medium  EX_cpd00137_m      zero  3.618345e-06  exchanges
1113  EX_cpd00210_m  medium  EX_cpd00137_m      zero  2.593974e-06  exchanges
1114  EX_cpd00380_m  medium  EX_cpd00137_m      zero  1.647049e-06  exchanges
1117  EX_cpd00006_m  medium  EX_cpd00137_m      zero  3.731899e-07  exchanges
1118  EX_cpd00138_m  medium  EX_cpd00137_m      zero  1.115990e-06  exchanges
1119  EX_cpd00180_m  medium  EX_cpd00137_m      zero  1.436152e-05  exchanges
1120  EX_cpd00038_m  medium  EX_cpd00137_m      zero  3.135089e-06  exchanges
1122  EX_cpd00001_m  medium  EX_cpd00137_m   forward  1.001864e+00  exchanges
1123  EX_cpd00011_m  medium  EX_cpd00137_m   forward  1.353304e+00  exchanges
1124  EX_cpd00007_m  medium  EX_cpd00137_m   reverse  1.232540e+00  exchanges
1126  EX_cpd00141_m  medium  EX_cpd00137_m      zero  2.419491e-06  exchanges
1127  EX_cpd00073_m  medium  EX_cpd00137_m      zero  8.039518e-05  exchanges
1128  EX_cpd01861_m  medium  EX_cpd00137_m      zero  3.259901e-08  exchanges
1129  EX_cpd00453_m  medium  EX_cpd00137_m      zero  3.259814e-08  exchanges
1130  EX_cpd00071_m  medium  EX_cpd00137_m      zero  2.881787e-06  exchanges
1131  EX_cpd00150_m  medium  EX_cpd00137_m      zero  1.716900e-08  exchanges
1134  EX_cpd00363_m  medium  EX_cpd00137_m      zero  2.424539e-06  exchanges
1135  EX_cpd00055_m  medium  EX_cpd00137_m      zero  7.050643e-06  exchanges
1136  EX_cpd00448_m  medium  EX_cpd00137_m      zero  2.257748e-06  exchanges
1137  EX_cpd00025_m  medium  EX_cpd00137_m   forward  2.604658e+00  exchanges
1138  EX_cpd00239_m  medium  EX_cpd00137_m      zero  2.982030e-05  exchanges
1139  EX_cpd11640_m  medium  EX_cpd00137_m      zero  1.544319e-05  exchanges
1140  EX_cpd00359_m  medium  EX_cpd00137_m      zero  7.815592e-07  exchanges
1141  EX_cpd00659_m  medium  EX_cpd00137_m      zero  2.547274e-05  exchanges
1142  EX_cpd00418_m  medium  EX_cpd00137_m      zero  1.567437e-04  exchanges
1143  EX_cpd00371_m  medium  EX_cpd00137_m      zero  2.878970e-06  exchanges
1145  EX_cpd00324_m  medium  EX_cpd00137_m      zero  7.072518e-06  exchanges
1148  EX_cpd00116_m  medium  EX_cpd00137_m      zero  4.819950e-06  exchanges
1150  EX_cpd11632_m  medium  EX_cpd00137_m   reverse -6.239453e-12  exchanges
1154  EX_cpd00030_m  medium  EX_cpd00137_m   reverse  8.535367e-01  exchanges
1155  EX_cpd11451_m  medium  EX_cpd00137_m      zero  8.025429e-08  exchanges
1156  EX_cpd11606_m  medium  EX_cpd00137_m      zero  4.784869e-08  exchanges
1157  EX_cpd00121_m  medium  EX_cpd00137_m      zero  8.833780e-06  exchanges
1158  EX_cpd00314_m  medium  EX_cpd00137_m      zero  1.039350e-06  exchanges
1159  EX_cpd00588_m  medium  EX_cpd00137_m      zero  1.045869e-06  exchanges
1160  EX_cpd00322_m  medium  EX_cpd00137_m      zero  1.005697e-06  exchanges
1161  EX_cpd00107_m  medium  EX_cpd00137_m      zero  9.788093e-07  exchanges
1162  EX_cpd00060_m  medium  EX_cpd00137_m      zero  1.429959e-06  exchanges
1163  EX_cpd00066_m  medium  EX_cpd00137_m      zero  7.483410e-07  exchanges
1164  EX_cpd00065_m  medium  EX_cpd00137_m      zero  6.146182e-07  exchanges
1165  EX_cpd00069_m  medium  EX_cpd00137_m      zero  8.758161e-07  exchanges
1166  EX_cpd00249_m  medium  EX_cpd00137_m      zero  9.208322e-07  exchanges
1168  EX_cpd00366_m  medium  EX_cpd00137_m      zero  1.193980e-06  exchanges
1169  EX_cpd00222_m  medium  EX_cpd00137_m      zero  1.214865e-06  exchanges
1170  EX_cpd00105_m  medium  EX_cpd00137_m      zero  1.294604e-06  exchanges
1171  EX_cpd00154_m  medium  EX_cpd00137_m      zero  1.294048e-06  exchanges
1172  EX_cpd00003_m  medium  EX_cpd00137_m      zero  3.818083e-07  exchanges
1173  EX_cpd00017_m  medium  EX_cpd00137_m      zero  5.029924e-07  exchanges
1174  EX_cpd00098_m  medium  EX_cpd00137_m      zero  2.219023e-08  exchanges
1175  EX_cpd00117_m  medium  EX_cpd00137_m      zero  2.418165e-06  exchanges
1176  EX_cpd00220_m  medium  EX_cpd00137_m      zero  5.588724e-07  exchanges
1177  EX_cpd00277_m  medium  EX_cpd00137_m      zero  8.069818e-07  exchanges
1178  EX_cpd00281_m  medium  EX_cpd00137_m      zero  1.651327e-06  exchanges
1179  EX_cpd00367_m  medium  EX_cpd00137_m      zero  9.218429e-07  exchanges
1180  EX_cpd00550_m  medium  EX_cpd00137_m      zero  2.791089e-06  exchanges
1181  EX_cpd00644_m  medium  EX_cpd00137_m      zero  8.127476e-07  exchanges
1184  EX_cpd00208_m  medium  EX_cpd00137_m      zero  3.162395e-08  exchanges